import uuid
from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

from app.models.audit_log import AuditLog
from app.repositories.audit_repository import AuditRepository


class AuditAction:
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    LOGIN_FAILED = "LOGIN_FAILED"
    REGISTER = "REGISTER"
    TOKEN_REFRESH = "TOKEN_REFRESH"
    COMPANY_SWITCH = "COMPANY_SWITCH"

    COMPANY_CREATE = "COMPANY_CREATE"
    COMPANY_UPDATE = "COMPANY_UPDATE"

    USER_CREATE = "USER_CREATE"
    USER_UPDATE = "USER_UPDATE"
    USER_DEACTIVATE = "USER_DEACTIVATE"
    USER_ROLE_ASSIGN = "USER_ROLE_ASSIGN"

    DOCUMENT_UPLOAD = "DOCUMENT_UPLOAD"
    DOCUMENT_DOWNLOAD = "DOCUMENT_DOWNLOAD"
    DOCUMENT_UPDATE = "DOCUMENT_UPDATE"
    DOCUMENT_ARCHIVE = "DOCUMENT_ARCHIVE"
    DOCUMENT_RESTORE = "DOCUMENT_RESTORE"
    DOCUMENT_DELETE = "DOCUMENT_DELETE"
    DOCUMENT_DUPLICATE_ATTEMPT = "DOCUMENT_DUPLICATE_ATTEMPT"
    DOCUMENT_ACCESS_DENIED = "DOCUMENT_ACCESS_DENIED"

    # --- Accounting (Phase 3) ---
    ACCOUNTING_CREATE = "CREATE"
    ACCOUNTING_UPDATE = "UPDATE"
    ACCOUNTING_DELETE = "DELETE"
    ACCOUNTING_POST = "POST"
    ACCOUNTING_CANCEL = "CANCEL"

    IMPORT_CREATE = "IMPORT"
    IMPORT_COMMIT = "IMPORT_COMMIT"
    IMPORT_FAILED = "IMPORT_FAILED"
    DUPLICATE_DETECTED = "DUPLICATE_DETECTED"

    OPENING_BALANCE_CREATED = "OPENING_BALANCE_CREATED"
    PERIOD_CLOSED = "PERIOD_CLOSED"
    PERIOD_LOCKED = "PERIOD_LOCKED"

    # --- GST (Phase 4) ---
    GST_PROFILE_CREATED = "GST_PROFILE_CREATED"
    GST_PROFILE_UPDATED = "GST_PROFILE_UPDATED"
    GST_TAX_RATE_CREATED = "GST_TAX_RATE_CREATED"
    GST_TAX_RATE_UPDATED = "GST_TAX_RATE_UPDATED"
    GST_RETURN_PERIOD_CREATED = "GST_RETURN_PERIOD_CREATED"

    GST_RETURN_GENERATED = "GST_RETURN_GENERATED"
    GST_RETURN_VALIDATED = "GST_RETURN_VALIDATED"
    GST_RETURN_APPROVED = "GST_RETURN_APPROVED"
    GST_RETURN_CHANGES_REQUESTED = "GST_RETURN_CHANGES_REQUESTED"
    GST_RETURN_FINALIZED = "GST_RETURN_FINALIZED"

    GSTR2B_IMPORTED = "GSTR2B_IMPORTED"
    GSTR2B_RECONCILED = "GSTR2B_RECONCILED"

    ITC_REVIEWED = "ITC_REVIEWED"
    ITC_APPROVED = "ITC_APPROVED"
    ITC_REJECTED = "ITC_REJECTED"

    GST_REVIEW_NOTE_CREATED = "GST_REVIEW_NOTE_CREATED"
    GST_REVIEW_NOTE_RESOLVED = "GST_REVIEW_NOTE_RESOLVED"

    GST_EXPORT_GENERATED = "GST_EXPORT_GENERATED"

    # --- TDS (Phase 5) ---
    TDS_PROFILE_CREATED = "TDS_PROFILE_CREATED"
    TDS_PROFILE_UPDATED = "TDS_PROFILE_UPDATED"

    DEDUCTEE_CREATED = "DEDUCTEE_CREATED"
    DEDUCTEE_UPDATED = "DEDUCTEE_UPDATED"

    TDS_RULE_CREATED = "TDS_RULE_CREATED"
    TDS_RULE_UPDATED = "TDS_RULE_UPDATED"

    TDS_TRANSACTION_CREATED = "TDS_TRANSACTION_CREATED"
    TDS_TRANSACTION_CALCULATED = "TDS_TRANSACTION_CALCULATED"
    TDS_TRANSACTION_DEDUCTED = "TDS_TRANSACTION_DEDUCTED"
    TDS_TRANSACTION_CANCELLED = "TDS_TRANSACTION_CANCELLED"

    TDS_CHALLAN_CREATED = "TDS_CHALLAN_CREATED"
    TDS_CHALLAN_ALLOCATED = "TDS_CHALLAN_ALLOCATED"
    TDS_CHALLAN_RECONCILED = "TDS_CHALLAN_RECONCILED"

    TDS_IMPORT_STARTED = "TDS_IMPORT_STARTED"
    TDS_IMPORT_COMMITTED = "TDS_IMPORT_COMMITTED"
    TDS_IMPORT_FAILED = "TDS_IMPORT_FAILED"

    TDS_RETURN_PERIOD_CREATED = "TDS_RETURN_PERIOD_CREATED"
    TDS_RETURN_GENERATED = "TDS_RETURN_GENERATED"
    TDS_RETURN_VALIDATED = "TDS_RETURN_VALIDATED"
    TDS_RETURN_APPROVED = "TDS_RETURN_APPROVED"
    TDS_RETURN_CHANGES_REQUESTED = "TDS_RETURN_CHANGES_REQUESTED"
    TDS_RETURN_FINALIZED = "TDS_RETURN_FINALIZED"

    TDS_REVIEW_CREATED = "TDS_REVIEW_CREATED"
    TDS_REVIEW_RESOLVED = "TDS_REVIEW_RESOLVED"

    TDS_EXPORT_GENERATED = "TDS_EXPORT_GENERATED"

    # --- Bank Reconciliation (Phase 6) ---
    BANK_ACCOUNT_CREATED = "BANK_ACCOUNT_CREATED"
    BANK_ACCOUNT_UPDATED = "BANK_ACCOUNT_UPDATED"

    BANK_STATEMENT_IMPORTED = "BANK_STATEMENT_IMPORTED"
    BANK_STATEMENT_ARCHIVED = "BANK_STATEMENT_ARCHIVED"

    BANK_TRANSACTION_IMPORTED = "BANK_TRANSACTION_IMPORTED"
    BANK_TRANSACTION_EXCLUDED = "BANK_TRANSACTION_EXCLUDED"

    BANK_TRANSACTION_MATCHED = "BANK_TRANSACTION_MATCHED"
    BANK_TRANSACTION_UNMATCHED = "BANK_TRANSACTION_UNMATCHED"

    BANK_MATCH_CREATED = "BANK_MATCH_CREATED"
    BANK_MATCH_REVERSED = "BANK_MATCH_REVERSED"

    BANK_RECONCILIATION_STARTED = "BANK_RECONCILIATION_STARTED"
    BANK_RECONCILIATION_MATCHING_RUN = "BANK_RECONCILIATION_MATCHING_RUN"
    BANK_RECONCILIATION_SUBMITTED = "BANK_RECONCILIATION_SUBMITTED"
    BANK_RECONCILIATION_APPROVED = "BANK_RECONCILIATION_APPROVED"
    BANK_RECONCILIATION_REJECTED = "BANK_RECONCILIATION_REJECTED"
    BANK_RECONCILIATION_LOCKED = "BANK_RECONCILIATION_LOCKED"

    BANK_ADJUSTMENT_CREATED = "BANK_ADJUSTMENT_CREATED"

    BANK_EXPORT_GENERATED = "BANK_EXPORT_GENERATED"

    # --- CA/Auditor Workflow (Phase 7) ---
    AUDIT_ENGAGEMENT_CREATED = "AUDIT_ENGAGEMENT_CREATED"
    AUDIT_ENGAGEMENT_UPDATED = "AUDIT_ENGAGEMENT_UPDATED"
    AUDIT_ASSIGNMENT_CREATED = "AUDIT_ASSIGNMENT_CREATED"
    AUDIT_ASSIGNMENT_REMOVED = "AUDIT_ASSIGNMENT_REMOVED"

    AUDIT_CHECKLIST_CREATED = "AUDIT_CHECKLIST_CREATED"
    AUDIT_CHECKLIST_UPDATED = "AUDIT_CHECKLIST_UPDATED"
    AUDIT_CHECKLIST_COMPLETED = "AUDIT_CHECKLIST_COMPLETED"

    AUDIT_FINDING_CREATED = "AUDIT_FINDING_CREATED"
    AUDIT_FINDING_UPDATED = "AUDIT_FINDING_UPDATED"
    AUDIT_FINDING_ASSIGNED = "AUDIT_FINDING_ASSIGNED"
    AUDIT_FINDING_STATUS_CHANGED = "AUDIT_FINDING_STATUS_CHANGED"

    AUDIT_FINDING_COMMENT_ADDED = "AUDIT_FINDING_COMMENT_ADDED"
    AUDIT_FINDING_RESPONSE_SUBMITTED = "AUDIT_FINDING_RESPONSE_SUBMITTED"
    AUDIT_FINDING_RESPONSE_REVIEWED = "AUDIT_FINDING_RESPONSE_REVIEWED"

    AUDIT_FINDING_EVIDENCE_ADDED = "AUDIT_FINDING_EVIDENCE_ADDED"
    AUDIT_FINDING_EVIDENCE_REMOVED = "AUDIT_FINDING_EVIDENCE_REMOVED"

    AUDIT_REVIEW_STARTED = "AUDIT_REVIEW_STARTED"
    AUDIT_REVIEW_COMPLETED = "AUDIT_REVIEW_COMPLETED"
    AUDIT_REVIEW_RETURNED = "AUDIT_REVIEW_RETURNED"

    AUDIT_ENGAGEMENT_APPROVED = "AUDIT_ENGAGEMENT_APPROVED"
    AUDIT_SIGNOFF_CREATED = "AUDIT_SIGNOFF_CREATED"
    AUDIT_ENGAGEMENT_CLOSED = "AUDIT_ENGAGEMENT_CLOSED"
    AUDIT_ENGAGEMENT_LOCKED = "AUDIT_ENGAGEMENT_LOCKED"
    AUDIT_ENGAGEMENT_CANCELLED = "AUDIT_ENGAGEMENT_CANCELLED"

    AUDIT_WORKFLOW_EXPORT_GENERATED = "AUDIT_WORKFLOW_EXPORT_GENERATED"


class AuditService:
    def __init__(self, db: AsyncSession) -> None:
        self.db = db
        self.repo = AuditRepository(db)

    async def log(
        self,
        *,
        action: str,
        user_id: uuid.UUID | None,
        company_id: uuid.UUID | None = None,
        resource_type: str | None = None,
        resource_id: str | None = None,
        description: str | None = None,
        ip_address: str | None = None,
        user_agent: str | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> AuditLog:
        log_entry = AuditLog(
            company_id=company_id,
            user_id=user_id,
            action=action,
            resource_type=resource_type,
            resource_id=resource_id,
            description=description,
            ip_address=ip_address,
            user_agent=user_agent,
            log_metadata=metadata,
        )
        return await self.repo.create(log_entry)
