import uuid
from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

from app.models.audit_log import AuditLog
from app.repositories.audit_repository import AuditRepository


class AuditAction:
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    LOGIN_FAILED = "LOGIN_FAILED"
    REGISTER = "REGISTER"
    TOKEN_REFRESH = "TOKEN_REFRESH"
    COMPANY_SWITCH = "COMPANY_SWITCH"

    COMPANY_CREATE = "COMPANY_CREATE"
    COMPANY_UPDATE = "COMPANY_UPDATE"

    USER_CREATE = "USER_CREATE"
    USER_UPDATE = "USER_UPDATE"
    USER_DEACTIVATE = "USER_DEACTIVATE"
    USER_ROLE_ASSIGN = "USER_ROLE_ASSIGN"

    DOCUMENT_UPLOAD = "DOCUMENT_UPLOAD"
    DOCUMENT_DOWNLOAD = "DOCUMENT_DOWNLOAD"
    DOCUMENT_UPDATE = "DOCUMENT_UPDATE"
    DOCUMENT_ARCHIVE = "DOCUMENT_ARCHIVE"
    DOCUMENT_RESTORE = "DOCUMENT_RESTORE"
    DOCUMENT_DELETE = "DOCUMENT_DELETE"
    DOCUMENT_DUPLICATE_ATTEMPT = "DOCUMENT_DUPLICATE_ATTEMPT"
    DOCUMENT_ACCESS_DENIED = "DOCUMENT_ACCESS_DENIED"

    # --- Accounting (Phase 3) ---
    ACCOUNTING_CREATE = "CREATE"
    ACCOUNTING_UPDATE = "UPDATE"
    ACCOUNTING_DELETE = "DELETE"
    ACCOUNTING_POST = "POST"
    ACCOUNTING_CANCEL = "CANCEL"

    IMPORT_CREATE = "IMPORT"
    IMPORT_COMMIT = "IMPORT_COMMIT"
    IMPORT_FAILED = "IMPORT_FAILED"
    DUPLICATE_DETECTED = "DUPLICATE_DETECTED"

    OPENING_BALANCE_CREATED = "OPENING_BALANCE_CREATED"
    PERIOD_CLOSED = "PERIOD_CLOSED"
    PERIOD_LOCKED = "PERIOD_LOCKED"

    # --- GST (Phase 4) ---
    GST_PROFILE_CREATED = "GST_PROFILE_CREATED"
    GST_PROFILE_UPDATED = "GST_PROFILE_UPDATED"
    GST_TAX_RATE_CREATED = "GST_TAX_RATE_CREATED"
    GST_TAX_RATE_UPDATED = "GST_TAX_RATE_UPDATED"
    GST_RETURN_PERIOD_CREATED = "GST_RETURN_PERIOD_CREATED"

    GST_RETURN_GENERATED = "GST_RETURN_GENERATED"
    GST_RETURN_VALIDATED = "GST_RETURN_VALIDATED"
    GST_RETURN_APPROVED = "GST_RETURN_APPROVED"
    GST_RETURN_CHANGES_REQUESTED = "GST_RETURN_CHANGES_REQUESTED"
    GST_RETURN_FINALIZED = "GST_RETURN_FINALIZED"

    GSTR2B_IMPORTED = "GSTR2B_IMPORTED"
    GSTR2B_RECONCILED = "GSTR2B_RECONCILED"

    ITC_REVIEWED = "ITC_REVIEWED"
    ITC_APPROVED = "ITC_APPROVED"
    ITC_REJECTED = "ITC_REJECTED"

    GST_REVIEW_NOTE_CREATED = "GST_REVIEW_NOTE_CREATED"
    GST_REVIEW_NOTE_RESOLVED = "GST_REVIEW_NOTE_RESOLVED"

    GST_EXPORT_GENERATED = "GST_EXPORT_GENERATED"

    # --- TDS (Phase 5) ---
    TDS_PROFILE_CREATED = "TDS_PROFILE_CREATED"
    TDS_PROFILE_UPDATED = "TDS_PROFILE_UPDATED"

    DEDUCTEE_CREATED = "DEDUCTEE_CREATED"
    DEDUCTEE_UPDATED = "DEDUCTEE_UPDATED"

    TDS_RULE_CREATED = "TDS_RULE_CREATED"
    TDS_RULE_UPDATED = "TDS_RULE_UPDATED"

    TDS_TRANSACTION_CREATED = "TDS_TRANSACTION_CREATED"
    TDS_TRANSACTION_CALCULATED = "TDS_TRANSACTION_CALCULATED"
    TDS_TRANSACTION_DEDUCTED = "TDS_TRANSACTION_DEDUCTED"
    TDS_TRANSACTION_CANCELLED = "TDS_TRANSACTION_CANCELLED"

    TDS_CHALLAN_CREATED = "TDS_CHALLAN_CREATED"
    TDS_CHALLAN_ALLOCATED = "TDS_CHALLAN_ALLOCATED"
    TDS_CHALLAN_RECONCILED = "TDS_CHALLAN_RECONCILED"

    TDS_IMPORT_STARTED = "TDS_IMPORT_STARTED"
    TDS_IMPORT_COMMITTED = "TDS_IMPORT_COMMITTED"
    TDS_IMPORT_FAILED = "TDS_IMPORT_FAILED"

    TDS_RETURN_PERIOD_CREATED = "TDS_RETURN_PERIOD_CREATED"
    TDS_RETURN_GENERATED = "TDS_RETURN_GENERATED"
    TDS_RETURN_VALIDATED = "TDS_RETURN_VALIDATED"
    TDS_RETURN_APPROVED = "TDS_RETURN_APPROVED"
    TDS_RETURN_CHANGES_REQUESTED = "TDS_RETURN_CHANGES_REQUESTED"
    TDS_RETURN_FINALIZED = "TDS_RETURN_FINALIZED"

    TDS_REVIEW_CREATED = "TDS_REVIEW_CREATED"
    TDS_REVIEW_RESOLVED = "TDS_REVIEW_RESOLVED"

    TDS_EXPORT_GENERATED = "TDS_EXPORT_GENERATED"

    # --- Bank Reconciliation (Phase 6) ---
    BANK_ACCOUNT_CREATED = "BANK_ACCOUNT_CREATED"
    BANK_ACCOUNT_UPDATED = "BANK_ACCOUNT_UPDATED"

    BANK_STATEMENT_IMPORTED = "BANK_STATEMENT_IMPORTED"
    BANK_STATEMENT_ARCHIVED = "BANK_STATEMENT_ARCHIVED"

    BANK_TRANSACTION_IMPORTED = "BANK_TRANSACTION_IMPORTED"
    BANK_TRANSACTION_EXCLUDED = "BANK_TRANSACTION_EXCLUDED"

    BANK_TRANSACTION_MATCHED = "BANK_TRANSACTION_MATCHED"
    BANK_TRANSACTION_UNMATCHED = "BANK_TRANSACTION_UNMATCHED"

    BANK_MATCH_CREATED = "BANK_MATCH_CREATED"
    BANK_MATCH_REVERSED = "BANK_MATCH_REVERSED"

    BANK_RECONCILIATION_STARTED = "BANK_RECONCILIATION_STARTED"
    BANK_RECONCILIATION_MATCHING_RUN = "BANK_RECONCILIATION_MATCHING_RUN"
    BANK_RECONCILIATION_SUBMITTED = "BANK_RECONCILIATION_SUBMITTED"
    BANK_RECONCILIATION_APPROVED = "BANK_RECONCILIATION_APPROVED"
    BANK_RECONCILIATION_REJECTED = "BANK_RECONCILIATION_REJECTED"
    BANK_RECONCILIATION_LOCKED = "BANK_RECONCILIATION_LOCKED"

    BANK_ADJUSTMENT_CREATED = "BANK_ADJUSTMENT_CREATED"

    BANK_EXPORT_GENERATED = "BANK_EXPORT_GENERATED"

    # --- CA/Auditor Workflow (Phase 7) ---
    AUDIT_ENGAGEMENT_CREATED = "AUDIT_ENGAGEMENT_CREATED"
    AUDIT_ENGAGEMENT_UPDATED = "AUDIT_ENGAGEMENT_UPDATED"
    AUDIT_ASSIGNMENT_CREATED = "AUDIT_ASSIGNMENT_CREATED"
    AUDIT_ASSIGNMENT_REMOVED = "AUDIT_ASSIGNMENT_REMOVED"

    AUDIT_CHECKLIST_CREATED = "AUDIT_CHECKLIST_CREATED"
    AUDIT_CHECKLIST_UPDATED = "AUDIT_CHECKLIST_UPDATED"
    AUDIT_CHECKLIST_COMPLETED = "AUDIT_CHECKLIST_COMPLETED"

    AUDIT_FINDING_CREATED = "AUDIT_FINDING_CREATED"
    AUDIT_FINDING_UPDATED = "AUDIT_FINDING_UPDATED"
    AUDIT_FINDING_ASSIGNED = "AUDIT_FINDING_ASSIGNED"
    AUDIT_FINDING_STATUS_CHANGED = "AUDIT_FINDING_STATUS_CHANGED"

    AUDIT_FINDING_COMMENT_ADDED = "AUDIT_FINDING_COMMENT_ADDED"
    AUDIT_FINDING_RESPONSE_SUBMITTED = "AUDIT_FINDING_RESPONSE_SUBMITTED"
    AUDIT_FINDING_RESPONSE_REVIEWED = "AUDIT_FINDING_RESPONSE_REVIEWED"

    AUDIT_FINDING_EVIDENCE_ADDED = "AUDIT_FINDING_EVIDENCE_ADDED"
    AUDIT_FINDING_EVIDENCE_REMOVED = "AUDIT_FINDING_EVIDENCE_REMOVED"

    AUDIT_REVIEW_STARTED = "AUDIT_REVIEW_STARTED"
    AUDIT_REVIEW_COMPLETED = "AUDIT_REVIEW_COMPLETED"
    AUDIT_REVIEW_RETURNED = "AUDIT_REVIEW_RETURNED"

    AUDIT_ENGAGEMENT_APPROVED = "AUDIT_ENGAGEMENT_APPROVED"
    AUDIT_SIGNOFF_CREATED = "AUDIT_SIGNOFF_CREATED"
    AUDIT_ENGAGEMENT_CLOSED = "AUDIT_ENGAGEMENT_CLOSED"
    AUDIT_ENGAGEMENT_LOCKED = "AUDIT_ENGAGEMENT_LOCKED"
    AUDIT_ENGAGEMENT_CANCELLED = "AUDIT_ENGAGEMENT_CANCELLED"

    AUDIT_WORKFLOW_EXPORT_GENERATED = "AUDIT_WORKFLOW_EXPORT_GENERATED"

    # --- Income Tax (Phase 8) ---
    INCOME_TAX_PROFILE_CREATED = "INCOME_TAX_PROFILE_CREATED"
    INCOME_TAX_PROFILE_UPDATED = "INCOME_TAX_PROFILE_UPDATED"

    TAX_INCOME_CREATED = "TAX_INCOME_CREATED"
    TAX_INCOME_UPDATED = "TAX_INCOME_UPDATED"
    TAX_INCOME_DELETED = "TAX_INCOME_DELETED"

    TAX_DEDUCTION_CREATED = "TAX_DEDUCTION_CREATED"
    TAX_DEDUCTION_UPDATED = "TAX_DEDUCTION_UPDATED"
    TAX_DEDUCTION_DELETED = "TAX_DEDUCTION_DELETED"

    CAPITAL_GAIN_CREATED = "CAPITAL_GAIN_CREATED"
    CAPITAL_GAIN_UPDATED = "CAPITAL_GAIN_UPDATED"
    CAPITAL_GAIN_DELETED = "CAPITAL_GAIN_DELETED"

    TAX_LOSS_CREATED = "TAX_LOSS_CREATED"
    TAX_LOSS_SET_OFF = "TAX_LOSS_SET_OFF"

    TAX_CREDIT_CREATED = "TAX_CREDIT_CREATED"
    TAX_PAYMENT_CREATED = "TAX_PAYMENT_CREATED"
    TAX_PAYMENT_UPDATED = "TAX_PAYMENT_UPDATED"

    TAX_COMPUTATION_CREATED = "TAX_COMPUTATION_CREATED"
    TAX_COMPUTATION_CALCULATED = "TAX_COMPUTATION_CALCULATED"
    TAX_COMPUTATION_SUBMITTED = "TAX_COMPUTATION_SUBMITTED"
    TAX_COMPUTATION_APPROVED = "TAX_COMPUTATION_APPROVED"
    TAX_COMPUTATION_LOCKED = "TAX_COMPUTATION_LOCKED"
    TAX_COMPUTATION_CANCELLED = "TAX_COMPUTATION_CANCELLED"

    ITR_PREPARATION_CREATED = "ITR_PREPARATION_CREATED"
    ITR_VALIDATED = "ITR_VALIDATED"
    ITR_SUBMITTED_FOR_REVIEW = "ITR_SUBMITTED_FOR_REVIEW"
    ITR_APPROVED = "ITR_APPROVED"
    ITR_LOCKED = "ITR_LOCKED"

    INCOME_TAX_EXPORT_GENERATED = "INCOME_TAX_EXPORT_GENERATED"

    # --- Compliance Calendar / Tasks / Notifications (Phase 9) ---
    COMPLIANCE_RULE_CREATED = "COMPLIANCE_RULE_CREATED"
    COMPLIANCE_RULE_UPDATED = "COMPLIANCE_RULE_UPDATED"
    COMPLIANCE_RULE_ACTIVATED = "COMPLIANCE_RULE_ACTIVATED"
    COMPLIANCE_RULE_DEACTIVATED = "COMPLIANCE_RULE_DEACTIVATED"

    COMPLIANCE_OBLIGATION_CREATED = "COMPLIANCE_OBLIGATION_CREATED"
    COMPLIANCE_OBLIGATION_UPDATED = "COMPLIANCE_OBLIGATION_UPDATED"
    COMPLIANCE_TASK_GENERATED = "COMPLIANCE_TASK_GENERATED"

    COMPLIANCE_TASK_CREATED = "COMPLIANCE_TASK_CREATED"
    COMPLIANCE_TASK_UPDATED = "COMPLIANCE_TASK_UPDATED"
    COMPLIANCE_TASK_ASSIGNED = "COMPLIANCE_TASK_ASSIGNED"
    COMPLIANCE_TASK_STARTED = "COMPLIANCE_TASK_STARTED"
    COMPLIANCE_TASK_SUBMITTED = "COMPLIANCE_TASK_SUBMITTED"
    COMPLIANCE_TASK_COMPLETED = "COMPLIANCE_TASK_COMPLETED"
    COMPLIANCE_TASK_VERIFIED = "COMPLIANCE_TASK_VERIFIED"
    COMPLIANCE_TASK_RETURNED = "COMPLIANCE_TASK_RETURNED"
    COMPLIANCE_TASK_CANCELLED = "COMPLIANCE_TASK_CANCELLED"
    COMPLIANCE_TASK_LOCKED = "COMPLIANCE_TASK_LOCKED"

    COMPLIANCE_COMMENT_ADDED = "COMPLIANCE_COMMENT_ADDED"
    COMPLIANCE_EVIDENCE_ADDED = "COMPLIANCE_EVIDENCE_ADDED"
    COMPLIANCE_EVIDENCE_REMOVED = "COMPLIANCE_EVIDENCE_REMOVED"

    COMPLIANCE_EXPORT_GENERATED = "COMPLIANCE_EXPORT_GENERATED"

    NOTIFICATION_CREATED = "NOTIFICATION_CREATED"


class AuditService:
    def __init__(self, db: AsyncSession) -> None:
        self.db = db
        self.repo = AuditRepository(db)

    async def log(
        self,
        *,
        action: str,
        user_id: uuid.UUID | None,
        company_id: uuid.UUID | None = None,
        resource_type: str | None = None,
        resource_id: str | None = None,
        description: str | None = None,
        ip_address: str | None = None,
        user_agent: str | None = None,
        metadata: dict[str, Any] | None = None,
    ) -> AuditLog:
        log_entry = AuditLog(
            company_id=company_id,
            user_id=user_id,
            action=action,
            resource_type=resource_type,
            resource_id=resource_id,
            description=description,
            ip_address=ip_address,
            user_agent=user_agent,
            log_metadata=metadata,
        )
        return await self.repo.create(log_entry)
