"""add_bank_statement_import_support

Revision ID: 0324bbd7f4ef
Revises: 4cec63c02442
Create Date: 2026-09-18 12:22:07.347235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.types


# revision identifiers, used by Alembic.
revision: str = '0324bbd7f4ef'
down_revision: Union[str, None] = '4cec63c02442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_jobs', sa.Column('bank_statement_id', app.utils.types.GUID(), nullable=True))
    op.create_foreign_key(None, 'import_jobs', 'bank_statements', ['bank_statement_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'import_jobs', type_='foreignkey')
    op.drop_column('import_jobs', 'bank_statement_id')
    # ### end Alembic commands ###
