"""add accounting master data: financial years, periods, ledgers, customers, vendors, products

Revision ID: 0eb6f0de2823
Revises: 58b6997e4b78
Create Date: 2026-09-15 09:57:01.109603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.types


# revision identifiers, used by Alembic.
revision: str = '0eb6f0de2823'
down_revision: Union[str, None] = '58b6997e4b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('billing_address', sa.String(length=500), nullable=True),
    sa.Column('shipping_address', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_company_code', 'customers', ['company_id', 'code'], unique=True)
    op.create_index(op.f('ix_customers_company_id'), 'customers', ['company_id'], unique=False)
    op.create_index(op.f('ix_customers_gstin'), 'customers', ['gstin'], unique=False)
    op.create_table('financial_years',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='financialyearstatus', native_enum=False, length=10), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_years_company_id'), 'financial_years', ['company_id'], unique=False)
    op.create_index('ix_financial_years_unique_current', 'financial_years', ['company_id'], unique=True, postgresql_where='is_current = true', sqlite_where='is_current = 1')
    op.create_table('ledgers',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('ledger_type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'INCOME', 'EXPENSE', 'RECEIVABLE', 'PAYABLE', 'BANK', 'CASH', 'TAX', name='ledgertype', native_enum=False, length=20), nullable=False),
    sa.Column('parent_ledger_id', app.utils.types.GUID(), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('opening_balance_type', sa.Enum('DEBIT', 'CREDIT', name='balancetype', native_enum=False, length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_ledger_id'], ['ledgers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledgers_company_code', 'ledgers', ['company_id', 'code'], unique=True)
    op.create_index(op.f('ix_ledgers_company_id'), 'ledgers', ['company_id'], unique=False)
    op.create_index('ix_ledgers_company_name', 'ledgers', ['company_id', 'name'], unique=True)
    op.create_index(op.f('ix_ledgers_ledger_type'), 'ledgers', ['ledger_type'], unique=False)
    op.create_table('products_services',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('item_type', sa.Enum('PRODUCT', 'SERVICE', name='itemtype', native_enum=False, length=10), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('hsn_sac', sa.String(length=20), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_services_company_code', 'products_services', ['company_id', 'code'], unique=True)
    op.create_index(op.f('ix_products_services_company_id'), 'products_services', ['company_id'], unique=False)
    op.create_table('vendors',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vendors_company_code', 'vendors', ['company_id', 'code'], unique=True)
    op.create_index(op.f('ix_vendors_company_id'), 'vendors', ['company_id'], unique=False)
    op.create_index(op.f('ix_vendors_gstin'), 'vendors', ['gstin'], unique=False)
    op.create_table('accounting_periods',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'LOCKED', name='periodstatus', native_enum=False, length=10), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounting_periods_company_id'), 'accounting_periods', ['company_id'], unique=False)
    op.create_index(op.f('ix_accounting_periods_financial_year_id'), 'accounting_periods', ['financial_year_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounting_periods_financial_year_id'), table_name='accounting_periods')
    op.drop_index(op.f('ix_accounting_periods_company_id'), table_name='accounting_periods')
    op.drop_table('accounting_periods')
    op.drop_index(op.f('ix_vendors_gstin'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_company_id'), table_name='vendors')
    op.drop_index('ix_vendors_company_code', table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_products_services_company_id'), table_name='products_services')
    op.drop_index('ix_products_services_company_code', table_name='products_services')
    op.drop_table('products_services')
    op.drop_index(op.f('ix_ledgers_ledger_type'), table_name='ledgers')
    op.drop_index('ix_ledgers_company_name', table_name='ledgers')
    op.drop_index(op.f('ix_ledgers_company_id'), table_name='ledgers')
    op.drop_index('ix_ledgers_company_code', table_name='ledgers')
    op.drop_table('ledgers')
    op.drop_index('ix_financial_years_unique_current', table_name='financial_years', postgresql_where='is_current = true', sqlite_where='is_current = 1')
    op.drop_index(op.f('ix_financial_years_company_id'), table_name='financial_years')
    op.drop_table('financial_years')
    op.drop_index(op.f('ix_customers_gstin'), table_name='customers')
    op.drop_index(op.f('ix_customers_company_id'), table_name='customers')
    op.drop_index('ix_customers_company_code', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
