"""add_sez_and_export_fields

Revision ID: 21f14d138a81
Revises: 9f0530640b44
Create Date: 2026-09-24 16:09:55.381506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.types


# revision identifiers, used by Alembic.
revision: str = '21f14d138a81'
down_revision: Union[str, None] = '9f0530640b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_sez', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('customers', sa.Column('is_export', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('sales_invoices', sa.Column('export_type', sa.String(length=30), nullable=True))
    op.add_column('sales_invoices', sa.Column('shipping_bill_number', sa.String(length=50), nullable=True))
    op.add_column('sales_invoices', sa.Column('shipping_bill_date', sa.Date(), nullable=True))
    op.add_column('sales_invoices', sa.Column('port_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_invoices', 'port_code')
    op.drop_column('sales_invoices', 'shipping_bill_date')
    op.drop_column('sales_invoices', 'shipping_bill_number')
    op.drop_column('sales_invoices', 'export_type')
    op.drop_column('customers', 'is_export')
    op.drop_column('customers', 'is_sez')
    # ### end Alembic commands ###
