"""add accounting transactions: invoices, notes, payments, receipts, journals, opening balances, imports

Revision ID: 353108526d88
Revises: 0eb6f0de2823
Create Date: 2026-09-15 10:02:27.727104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.types


# revision identifiers, used by Alembic.
revision: str = '353108526d88'
down_revision: Union[str, None] = '0eb6f0de2823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('document_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=True),
    sa.Column('import_type', sa.Enum('SALES', 'PURCHASES', 'CUSTOMERS', 'VENDORS', 'PRODUCTS', 'PAYMENTS', 'RECEIPTS', 'LEDGERS', 'JOURNALS', 'TALLY', name='importtype', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PARSING', 'VALIDATING', 'READY', 'PROCESSING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED', 'CANCELLED', name='importstatus', native_enum=False, length=30), nullable=False),
    sa.Column('column_mapping', sa.JSON(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('successful_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', app.utils.types.GUID(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_company_id'), 'import_jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_import_jobs_document_id'), 'import_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_import_jobs_import_type'), 'import_jobs', ['import_type'], unique=False)
    op.create_index(op.f('ix_import_jobs_status'), 'import_jobs', ['status'], unique=False)
    op.create_table('journal_entries',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('journal_number', sa.String(length=50), nullable=False),
    sa.Column('journal_date', sa.Date(), nullable=False),
    sa.Column('narration', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'CANCELLED', name='transactionstatus', native_enum=False, length=10), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'CSV', 'EXCEL', 'TALLY', name='datasource', native_enum=False, length=10), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_company_id'), 'journal_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_financial_year_id'), 'journal_entries', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_status'), 'journal_entries', ['status'], unique=False)
    op.create_index('ix_journal_entries_unique_number', 'journal_entries', ['company_id', 'financial_year_id', 'journal_number'], unique=True)
    op.create_table('opening_balances',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('account_type', sa.Enum('LEDGER', 'CUSTOMER', 'VENDOR', name='openingbalanceaccounttype', native_enum=False, length=10), nullable=False),
    sa.Column('account_id', app.utils.types.GUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_type', sa.Enum('DEBIT', 'CREDIT', name='balancetype', native_enum=False, length=10), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opening_balances_company_id'), 'opening_balances', ['company_id'], unique=False)
    op.create_index(op.f('ix_opening_balances_financial_year_id'), 'opening_balances', ['financial_year_id'], unique=False)
    op.create_index('ix_opening_balances_unique', 'opening_balances', ['company_id', 'financial_year_id', 'account_type', 'account_id'], unique=True)
    op.create_table('payments',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('payment_number', sa.String(length=50), nullable=False),
    sa.Column('party_type', sa.Enum('CUSTOMER', 'VENDOR', 'OTHER', name='partytype', native_enum=False, length=10), nullable=True),
    sa.Column('party_id', app.utils.types.GUID(), nullable=True),
    sa.Column('ledger_id', app.utils.types.GUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_mode', sa.Enum('CASH', 'BANK', 'UPI', 'CHEQUE', 'CARD', 'OTHER', name='paymentmode', native_enum=False, length=10), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'CANCELLED', name='transactionstatus', native_enum=False, length=10), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'CSV', 'EXCEL', 'TALLY', name='datasource', native_enum=False, length=10), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_company_id'), 'payments', ['company_id'], unique=False)
    op.create_index(op.f('ix_payments_financial_year_id'), 'payments', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_payments_ledger_id'), 'payments', ['ledger_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index('ix_payments_unique_number', 'payments', ['company_id', 'financial_year_id', 'payment_number'], unique=True)
    op.create_table('purchase_invoices',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('vendor_id', app.utils.types.GUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('supplier_invoice_number', sa.String(length=50), nullable=True),
    sa.Column('supplier_invoice_date', sa.Date(), nullable=True),
    sa.Column('place_of_supply', sa.String(length=100), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cess_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'CANCELLED', name='transactionstatus', native_enum=False, length=10), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'CSV', 'EXCEL', 'TALLY', name='datasource', native_enum=False, length=10), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_purchase_invoices_company_date', 'purchase_invoices', ['company_id', 'invoice_date'], unique=False)
    op.create_index(op.f('ix_purchase_invoices_company_id'), 'purchase_invoices', ['company_id'], unique=False)
    op.create_index(op.f('ix_purchase_invoices_financial_year_id'), 'purchase_invoices', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_purchase_invoices_status'), 'purchase_invoices', ['status'], unique=False)
    op.create_index('ix_purchase_invoices_unique_number', 'purchase_invoices', ['company_id', 'financial_year_id', 'invoice_number'], unique=True)
    op.create_index(op.f('ix_purchase_invoices_vendor_id'), 'purchase_invoices', ['vendor_id'], unique=False)
    op.create_table('receipts',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('customer_id', app.utils.types.GUID(), nullable=False),
    sa.Column('ledger_id', app.utils.types.GUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_mode', sa.Enum('CASH', 'BANK', 'UPI', 'CHEQUE', 'CARD', 'OTHER', name='paymentmode', native_enum=False, length=10), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'CANCELLED', name='transactionstatus', native_enum=False, length=10), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'CSV', 'EXCEL', 'TALLY', name='datasource', native_enum=False, length=10), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_company_id'), 'receipts', ['company_id'], unique=False)
    op.create_index(op.f('ix_receipts_customer_id'), 'receipts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_receipts_financial_year_id'), 'receipts', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_receipts_ledger_id'), 'receipts', ['ledger_id'], unique=False)
    op.create_index(op.f('ix_receipts_status'), 'receipts', ['status'], unique=False)
    op.create_index('ix_receipts_unique_number', 'receipts', ['company_id', 'financial_year_id', 'receipt_number'], unique=True)
    op.create_table('sales_invoices',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('customer_id', app.utils.types.GUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('place_of_supply', sa.String(length=100), nullable=True),
    sa.Column('place_of_supply_state_code', sa.String(length=2), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cess_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('round_off', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'CANCELLED', name='transactionstatus', native_enum=False, length=10), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'CSV', 'EXCEL', 'TALLY', name='datasource', native_enum=False, length=10), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_invoices_company_date', 'sales_invoices', ['company_id', 'invoice_date'], unique=False)
    op.create_index(op.f('ix_sales_invoices_company_id'), 'sales_invoices', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_invoices_customer_id'), 'sales_invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_invoices_financial_year_id'), 'sales_invoices', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_sales_invoices_status'), 'sales_invoices', ['status'], unique=False)
    op.create_index('ix_sales_invoices_unique_number', 'sales_invoices', ['company_id', 'financial_year_id', 'invoice_number'], unique=True)
    op.create_table('credit_notes',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('note_type', sa.Enum('SALES', 'PURCHASE', name='notetype', native_enum=False, length=10), nullable=False),
    sa.Column('customer_id', app.utils.types.GUID(), nullable=True),
    sa.Column('vendor_id', app.utils.types.GUID(), nullable=True),
    sa.Column('reference_sales_invoice_id', app.utils.types.GUID(), nullable=True),
    sa.Column('reference_purchase_invoice_id', app.utils.types.GUID(), nullable=True),
    sa.Column('credit_note_number', sa.String(length=50), nullable=False),
    sa.Column('credit_note_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('taxable_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cess_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'CANCELLED', name='transactionstatus', native_enum=False, length=10), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'CSV', 'EXCEL', 'TALLY', name='datasource', native_enum=False, length=10), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reference_purchase_invoice_id'], ['purchase_invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reference_sales_invoice_id'], ['sales_invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_notes_company_id'), 'credit_notes', ['company_id'], unique=False)
    op.create_index(op.f('ix_credit_notes_financial_year_id'), 'credit_notes', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_credit_notes_status'), 'credit_notes', ['status'], unique=False)
    op.create_index('ix_credit_notes_unique_number', 'credit_notes', ['company_id', 'financial_year_id', 'credit_note_number'], unique=True)
    op.create_table('debit_notes',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('note_type', sa.Enum('SALES', 'PURCHASE', name='notetype', native_enum=False, length=10), nullable=False),
    sa.Column('customer_id', app.utils.types.GUID(), nullable=True),
    sa.Column('vendor_id', app.utils.types.GUID(), nullable=True),
    sa.Column('reference_sales_invoice_id', app.utils.types.GUID(), nullable=True),
    sa.Column('reference_purchase_invoice_id', app.utils.types.GUID(), nullable=True),
    sa.Column('debit_note_number', sa.String(length=50), nullable=False),
    sa.Column('debit_note_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('taxable_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cess_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'CANCELLED', name='transactionstatus', native_enum=False, length=10), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'CSV', 'EXCEL', 'TALLY', name='datasource', native_enum=False, length=10), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reference_purchase_invoice_id'], ['purchase_invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reference_sales_invoice_id'], ['sales_invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debit_notes_company_id'), 'debit_notes', ['company_id'], unique=False)
    op.create_index(op.f('ix_debit_notes_financial_year_id'), 'debit_notes', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_debit_notes_status'), 'debit_notes', ['status'], unique=False)
    op.create_index('ix_debit_notes_unique_number', 'debit_notes', ['company_id', 'financial_year_id', 'debit_note_number'], unique=True)
    op.create_table('import_errors',
    sa.Column('import_job_id', app.utils.types.GUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=False),
    sa.Column('raw_value', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_errors_import_job_id'), 'import_errors', ['import_job_id'], unique=False)
    op.create_table('import_rows',
    sa.Column('import_job_id', app.utils.types.GUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('normalized_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_record_id', app.utils.types.GUID(), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_rows_import_job_id'), 'import_rows', ['import_job_id'], unique=False)
    op.create_index('ix_import_rows_job_row', 'import_rows', ['import_job_id', 'row_number'], unique=False)
    op.create_table('journal_entry_lines',
    sa.Column('journal_entry_id', app.utils.types.GUID(), nullable=False),
    sa.Column('ledger_id', app.utils.types.GUID(), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entry_lines_journal_entry_id'), 'journal_entry_lines', ['journal_entry_id'], unique=False)
    op.create_index(op.f('ix_journal_entry_lines_ledger_id'), 'journal_entry_lines', ['ledger_id'], unique=False)
    op.create_table('purchase_invoice_items',
    sa.Column('purchase_invoice_id', app.utils.types.GUID(), nullable=False),
    sa.Column('product_service_id', app.utils.types.GUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('igst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cess_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cess_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_service_id'], ['products_services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_invoice_id'], ['purchase_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_invoice_items_purchase_invoice_id'), 'purchase_invoice_items', ['purchase_invoice_id'], unique=False)
    op.create_table('sales_invoice_items',
    sa.Column('sales_invoice_id', app.utils.types.GUID(), nullable=False),
    sa.Column('product_service_id', app.utils.types.GUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('igst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cess_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cess_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_service_id'], ['products_services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_invoice_id'], ['sales_invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_invoice_items_sales_invoice_id'), 'sales_invoice_items', ['sales_invoice_id'], unique=False)
    op.create_table('credit_note_items',
    sa.Column('credit_note_id', app.utils.types.GUID(), nullable=False),
    sa.Column('product_service_id', app.utils.types.GUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('igst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cess_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cess_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['credit_note_id'], ['credit_notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_service_id'], ['products_services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_note_items_credit_note_id'), 'credit_note_items', ['credit_note_id'], unique=False)
    op.create_table('debit_note_items',
    sa.Column('debit_note_id', app.utils.types.GUID(), nullable=False),
    sa.Column('product_service_id', app.utils.types.GUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sgst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('igst_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cess_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cess_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['debit_note_id'], ['debit_notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_service_id'], ['products_services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debit_note_items_debit_note_id'), 'debit_note_items', ['debit_note_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debit_note_items_debit_note_id'), table_name='debit_note_items')
    op.drop_table('debit_note_items')
    op.drop_index(op.f('ix_credit_note_items_credit_note_id'), table_name='credit_note_items')
    op.drop_table('credit_note_items')
    op.drop_index(op.f('ix_sales_invoice_items_sales_invoice_id'), table_name='sales_invoice_items')
    op.drop_table('sales_invoice_items')
    op.drop_index(op.f('ix_purchase_invoice_items_purchase_invoice_id'), table_name='purchase_invoice_items')
    op.drop_table('purchase_invoice_items')
    op.drop_index(op.f('ix_journal_entry_lines_ledger_id'), table_name='journal_entry_lines')
    op.drop_index(op.f('ix_journal_entry_lines_journal_entry_id'), table_name='journal_entry_lines')
    op.drop_table('journal_entry_lines')
    op.drop_index('ix_import_rows_job_row', table_name='import_rows')
    op.drop_index(op.f('ix_import_rows_import_job_id'), table_name='import_rows')
    op.drop_table('import_rows')
    op.drop_index(op.f('ix_import_errors_import_job_id'), table_name='import_errors')
    op.drop_table('import_errors')
    op.drop_index('ix_debit_notes_unique_number', table_name='debit_notes')
    op.drop_index(op.f('ix_debit_notes_status'), table_name='debit_notes')
    op.drop_index(op.f('ix_debit_notes_financial_year_id'), table_name='debit_notes')
    op.drop_index(op.f('ix_debit_notes_company_id'), table_name='debit_notes')
    op.drop_table('debit_notes')
    op.drop_index('ix_credit_notes_unique_number', table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_status'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_financial_year_id'), table_name='credit_notes')
    op.drop_index(op.f('ix_credit_notes_company_id'), table_name='credit_notes')
    op.drop_table('credit_notes')
    op.drop_index('ix_sales_invoices_unique_number', table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_status'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_financial_year_id'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_customer_id'), table_name='sales_invoices')
    op.drop_index(op.f('ix_sales_invoices_company_id'), table_name='sales_invoices')
    op.drop_index('ix_sales_invoices_company_date', table_name='sales_invoices')
    op.drop_table('sales_invoices')
    op.drop_index('ix_receipts_unique_number', table_name='receipts')
    op.drop_index(op.f('ix_receipts_status'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_ledger_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_financial_year_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_customer_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_company_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_purchase_invoices_vendor_id'), table_name='purchase_invoices')
    op.drop_index('ix_purchase_invoices_unique_number', table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_status'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_financial_year_id'), table_name='purchase_invoices')
    op.drop_index(op.f('ix_purchase_invoices_company_id'), table_name='purchase_invoices')
    op.drop_index('ix_purchase_invoices_company_date', table_name='purchase_invoices')
    op.drop_table('purchase_invoices')
    op.drop_index('ix_payments_unique_number', table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_ledger_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_financial_year_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_company_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_opening_balances_unique', table_name='opening_balances')
    op.drop_index(op.f('ix_opening_balances_financial_year_id'), table_name='opening_balances')
    op.drop_index(op.f('ix_opening_balances_company_id'), table_name='opening_balances')
    op.drop_table('opening_balances')
    op.drop_index('ix_journal_entries_unique_number', table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_status'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_financial_year_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_company_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_import_jobs_status'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_import_type'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_document_id'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_company_id'), table_name='import_jobs')
    op.drop_table('import_jobs')
    # ### end Alembic commands ###
