"""add_tds_return_workflow_and_review_notes

Revision ID: 358862d4761c
Revises: 65a7bad5e010
Create Date: 2026-09-18 10:20:23.905151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.types


# revision identifiers, used by Alembic.
revision: str = '358862d4761c'
down_revision: Union[str, None] = '65a7bad5e010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tds_return_periods',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('quarter', sa.Enum('Q1', 'Q2', 'Q3', 'Q4', name='tdsquarter', native_enum=False), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'APPROVED', 'FINALIZED', 'ARCHIVED', name='tdsreturnperiodstatus', native_enum=False, length=15), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tds_return_periods_company_id'), 'tds_return_periods', ['company_id'], unique=False)
    op.create_index(op.f('ix_tds_return_periods_financial_year_id'), 'tds_return_periods', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_tds_return_periods_status'), 'tds_return_periods', ['status'], unique=False)
    op.create_index('ix_tds_return_periods_unique', 'tds_return_periods', ['company_id', 'financial_year_id', 'quarter'], unique=True)
    op.create_table('tds_return_snapshots',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('return_period_id', app.utils.types.GUID(), nullable=False),
    sa.Column('return_type', sa.Enum('FORM_24Q', 'FORM_26Q', 'FORM_27Q', 'FORM_27EQ', name='tdsreturntype', native_enum=False, length=15), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'UNDER_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'FINALIZED', name='tdsreturnsnapshotstatus', native_enum=False, length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_by', app.utils.types.GUID(), nullable=True),
    sa.Column('summary_data', sa.JSON(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['return_period_id'], ['tds_return_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tds_return_snapshots_company_id'), 'tds_return_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_tds_return_snapshots_return_period_id'), 'tds_return_snapshots', ['return_period_id'], unique=False)
    op.create_index(op.f('ix_tds_return_snapshots_return_type'), 'tds_return_snapshots', ['return_type'], unique=False)
    op.create_index(op.f('ix_tds_return_snapshots_status'), 'tds_return_snapshots', ['status'], unique=False)
    op.create_index('ix_tds_return_snapshots_unique_version', 'tds_return_snapshots', ['return_period_id', 'return_type', 'version'], unique=True)
    op.create_table('tds_review_notes',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('return_period_id', app.utils.types.GUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='tdsreviewnotestatus', native_enum=False, length=10), nullable=False),
    sa.Column('created_by', app.utils.types.GUID(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_period_id'], ['tds_return_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tds_review_notes_company_id'), 'tds_review_notes', ['company_id'], unique=False)
    op.create_index('ix_tds_review_notes_entity', 'tds_review_notes', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_tds_review_notes_return_period_id'), 'tds_review_notes', ['return_period_id'], unique=False)
    op.create_index(op.f('ix_tds_review_notes_status'), 'tds_review_notes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tds_review_notes_status'), table_name='tds_review_notes')
    op.drop_index(op.f('ix_tds_review_notes_return_period_id'), table_name='tds_review_notes')
    op.drop_index('ix_tds_review_notes_entity', table_name='tds_review_notes')
    op.drop_index(op.f('ix_tds_review_notes_company_id'), table_name='tds_review_notes')
    op.drop_table('tds_review_notes')
    op.drop_index('ix_tds_return_snapshots_unique_version', table_name='tds_return_snapshots')
    op.drop_index(op.f('ix_tds_return_snapshots_status'), table_name='tds_return_snapshots')
    op.drop_index(op.f('ix_tds_return_snapshots_return_type'), table_name='tds_return_snapshots')
    op.drop_index(op.f('ix_tds_return_snapshots_return_period_id'), table_name='tds_return_snapshots')
    op.drop_index(op.f('ix_tds_return_snapshots_company_id'), table_name='tds_return_snapshots')
    op.drop_table('tds_return_snapshots')
    op.drop_index('ix_tds_return_periods_unique', table_name='tds_return_periods')
    op.drop_index(op.f('ix_tds_return_periods_status'), table_name='tds_return_periods')
    op.drop_index(op.f('ix_tds_return_periods_financial_year_id'), table_name='tds_return_periods')
    op.drop_index(op.f('ix_tds_return_periods_company_id'), table_name='tds_return_periods')
    op.drop_table('tds_return_periods')
    # ### end Alembic commands ###
