"""add_bank_reconciliation_tables

Revision ID: 4cec63c02442
Revises: 358862d4761c
Create Date: 2026-09-18 12:16:29.929286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.types


# revision identifiers, used by Alembic.
revision: str = '4cec63c02442'
down_revision: Union[str, None] = '358862d4761c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('ledger_id', app.utils.types.GUID(), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_number_masked', sa.String(length=30), nullable=False),
    sa.Column('account_type', sa.Enum('SAVINGS', 'CURRENT', 'CASH_CREDIT', 'OVERDRAFT', 'OTHER', name='bankaccounttype', native_enum=False, length=15), nullable=False),
    sa.Column('ifsc_code', sa.String(length=11), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('opening_balance_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_company_id'), 'bank_accounts', ['company_id'], unique=False)
    op.create_index('ix_bank_accounts_company_number', 'bank_accounts', ['company_id', 'account_number_masked'], unique=True)
    op.create_table('bank_reconciliations',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('bank_account_id', app.utils.types.GUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('book_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('bank_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'PENDING_REVIEW', 'RECONCILED', 'LOCKED', 'CANCELLED', name='bankreconciliationstatus', native_enum=False, length=15), nullable=False),
    sa.Column('started_by', app.utils.types.GUID(), nullable=False),
    sa.Column('reviewed_by', app.utils.types.GUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_reconciliations_bank_account_id'), 'bank_reconciliations', ['bank_account_id'], unique=False)
    op.create_index('ix_bank_reconciliations_company_account', 'bank_reconciliations', ['company_id', 'bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_reconciliations_company_id'), 'bank_reconciliations', ['company_id'], unique=False)
    op.create_index(op.f('ix_bank_reconciliations_status'), 'bank_reconciliations', ['status'], unique=False)
    op.create_table('bank_statements',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('bank_account_id', app.utils.types.GUID(), nullable=False),
    sa.Column('statement_name', sa.String(length=255), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('closing_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source_type', sa.Enum('CSV', 'XLSX', 'DOCUMENT', 'MANUAL', name='bankstatementsourcetype', native_enum=False, length=10), nullable=False),
    sa.Column('source_document_id', app.utils.types.GUID(), nullable=True),
    sa.Column('status', sa.Enum('IMPORTED', 'PROCESSING', 'READY', 'RECONCILING', 'RECONCILED', 'FAILED', 'ARCHIVED', name='bankstatementstatus', native_enum=False, length=15), nullable=False),
    sa.Column('created_by', app.utils.types.GUID(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_statements_bank_account_id'), 'bank_statements', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_statements_company_id'), 'bank_statements', ['company_id'], unique=False)
    op.create_index(op.f('ix_bank_statements_status'), 'bank_statements', ['status'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('bank_statement_id', app.utils.types.GUID(), nullable=False),
    sa.Column('bank_account_id', app.utils.types.GUID(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('reference_number', sa.String(length=255), nullable=True),
    sa.Column('cheque_number', sa.String(length=50), nullable=True),
    sa.Column('debit_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_after_transaction', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('transaction_type', sa.Enum('DEBIT', 'CREDIT', name='banktransactiontype', native_enum=False, length=10), nullable=False),
    sa.Column('normalized_description', sa.String(length=1000), nullable=True),
    sa.Column('normalized_reference', sa.String(length=255), nullable=True),
    sa.Column('external_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('reconciliation_status', sa.Enum('UNMATCHED', 'MATCH_SUGGESTED', 'PARTIALLY_MATCHED', 'MATCHED', 'MANUALLY_MATCHED', 'EXCLUDED', 'REVIEW_REQUIRED', name='banktransactionreconciliationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('credit_amount >= 0', name='ck_bank_transactions_credit_non_negative'),
    sa.CheckConstraint('debit_amount >= 0', name='ck_bank_transactions_debit_non_negative'),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['bank_statement_id'], ['bank_statements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_transactions_bank_account_id'), 'bank_transactions', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_bank_statement_id'), 'bank_transactions', ['bank_statement_id'], unique=False)
    op.create_index('ix_bank_transactions_company_account_date', 'bank_transactions', ['company_id', 'bank_account_id', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_bank_transactions_company_id'), 'bank_transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_reconciliation_status'), 'bank_transactions', ['reconciliation_status'], unique=False)
    op.create_index(op.f('ix_bank_transactions_reference_number'), 'bank_transactions', ['reference_number'], unique=False)
    op.create_index(op.f('ix_bank_transactions_transaction_date'), 'bank_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_bank_transactions_transaction_type'), 'bank_transactions', ['transaction_type'], unique=False)
    op.create_index('ix_bank_transactions_unique_checksum', 'bank_transactions', ['company_id', 'bank_account_id', 'checksum'], unique=True)
    op.create_table('bank_transaction_matches',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('bank_transaction_id', app.utils.types.GUID(), nullable=False),
    sa.Column('source_type', sa.Enum('PAYMENT', 'RECEIPT', 'JOURNAL_ENTRY', name='bankmatchsourcetype', native_enum=False, length=15), nullable=False),
    sa.Column('source_id', app.utils.types.GUID(), nullable=False),
    sa.Column('matched_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('match_type', sa.Enum('AUTO', 'MANUAL', 'PARTIAL', 'ADJUSTMENT', name='bankmatchtype', native_enum=False), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'REVERSED', name='bankmatchstatus', native_enum=False, length=10), nullable=False),
    sa.Column('matched_by', app.utils.types.GUID(), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('matched_amount > 0', name='ck_bank_transaction_matches_amount_positive'),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bank_transaction_matches_bank_txn', 'bank_transaction_matches', ['bank_transaction_id'], unique=False)
    op.create_index(op.f('ix_bank_transaction_matches_company_id'), 'bank_transaction_matches', ['company_id'], unique=False)
    op.create_index('ix_bank_transaction_matches_source', 'bank_transaction_matches', ['source_type', 'source_id'], unique=False)
    op.create_index(op.f('ix_bank_transaction_matches_status'), 'bank_transaction_matches', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_transaction_matches_status'), table_name='bank_transaction_matches')
    op.drop_index('ix_bank_transaction_matches_source', table_name='bank_transaction_matches')
    op.drop_index(op.f('ix_bank_transaction_matches_company_id'), table_name='bank_transaction_matches')
    op.drop_index('ix_bank_transaction_matches_bank_txn', table_name='bank_transaction_matches')
    op.drop_table('bank_transaction_matches')
    op.drop_index('ix_bank_transactions_unique_checksum', table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_transaction_type'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_transaction_date'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_reference_number'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_reconciliation_status'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_company_id'), table_name='bank_transactions')
    op.drop_index('ix_bank_transactions_company_account_date', table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_bank_statement_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_bank_account_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_bank_statements_status'), table_name='bank_statements')
    op.drop_index(op.f('ix_bank_statements_company_id'), table_name='bank_statements')
    op.drop_index(op.f('ix_bank_statements_bank_account_id'), table_name='bank_statements')
    op.drop_table('bank_statements')
    op.drop_index(op.f('ix_bank_reconciliations_status'), table_name='bank_reconciliations')
    op.drop_index(op.f('ix_bank_reconciliations_company_id'), table_name='bank_reconciliations')
    op.drop_index('ix_bank_reconciliations_company_account', table_name='bank_reconciliations')
    op.drop_index(op.f('ix_bank_reconciliations_bank_account_id'), table_name='bank_reconciliations')
    op.drop_table('bank_reconciliations')
    op.drop_index('ix_bank_accounts_company_number', table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_company_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
