"""add documents and document_links tables

Revision ID: 58b6997e4b78
Revises: 85dbd1c95215
Create Date: 2026-09-14 22:16:13.833557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.types


# revision identifiers, used by Alembic.
revision: str = '58b6997e4b78'
down_revision: Union[str, None] = '85dbd1c95215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('uploaded_by', app.utils.types.GUID(), nullable=False),
    sa.Column('archived_by', app.utils.types.GUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=150), nullable=False),
    sa.Column('file_extension', sa.String(length=10), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.Enum('SALES_INVOICE', 'PURCHASE_INVOICE', 'EXPENSE_BILL', 'BANK_STATEMENT', 'GST_REPORT', 'TDS_DOCUMENT', 'INCOME_TAX_DOCUMENT', 'FINANCIAL_STATEMENT', 'OTHER', name='documenttype', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'READY', 'REVIEW_REQUIRED', 'VERIFIED', 'ARCHIVED', 'FAILED', name='documentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['archived_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_checksum'), 'documents', ['checksum'], unique=False)
    op.create_index('ix_documents_company_checksum', 'documents', ['company_id', 'checksum'], unique=False)
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    op.create_index('ix_documents_company_uploaded_at', 'documents', ['company_id', 'uploaded_at'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('document_links',
    sa.Column('document_id', app.utils.types.GUID(), nullable=False),
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', app.utils.types.GUID(), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_links_document_id'), 'document_links', ['document_id'], unique=False)
    op.create_index('ix_document_links_resource', 'document_links', ['company_id', 'resource_type', 'resource_id'], unique=False)
    op.create_index('ix_document_links_unique', 'document_links', ['document_id', 'resource_type', 'resource_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_links_unique', table_name='document_links')
    op.drop_index('ix_document_links_resource', table_name='document_links')
    op.drop_index(op.f('ix_document_links_document_id'), table_name='document_links')
    op.drop_table('document_links')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index('ix_documents_company_uploaded_at', table_name='documents')
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.drop_index('ix_documents_company_checksum', table_name='documents')
    op.drop_index(op.f('ix_documents_checksum'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
