"""add_tds_payment_reconciliation

Revision ID: 65a7bad5e010
Revises: a47cccd57895
Create Date: 2026-09-18 10:09:16.371830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.types


# revision identifiers, used by Alembic.
revision: str = '65a7bad5e010'
down_revision: Union[str, None] = 'a47cccd57895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tds_payment_reconciliations',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('tds_transaction_id', app.utils.types.GUID(), nullable=True),
    sa.Column('tds_challan_id', app.utils.types.GUID(), nullable=True),
    sa.Column('status', sa.Enum('MATCHED', 'PARTIALLY_MATCHED', 'AMOUNT_MISMATCH', 'MISSING_CHALLAN', 'UNALLOCATED_PAYMENT', 'REVIEW_REQUIRED', name='tdsreconciliationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('allocated_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('variance_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tds_challan_id'], ['tds_challans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tds_transaction_id'], ['tds_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tds_payment_reconciliations_company_fy', 'tds_payment_reconciliations', ['company_id', 'financial_year_id'], unique=False)
    op.create_index(op.f('ix_tds_payment_reconciliations_company_id'), 'tds_payment_reconciliations', ['company_id'], unique=False)
    op.create_index(op.f('ix_tds_payment_reconciliations_financial_year_id'), 'tds_payment_reconciliations', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_tds_payment_reconciliations_status'), 'tds_payment_reconciliations', ['status'], unique=False)
    op.create_index(op.f('ix_tds_payment_reconciliations_tds_challan_id'), 'tds_payment_reconciliations', ['tds_challan_id'], unique=False)
    op.create_index(op.f('ix_tds_payment_reconciliations_tds_transaction_id'), 'tds_payment_reconciliations', ['tds_transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tds_payment_reconciliations_tds_transaction_id'), table_name='tds_payment_reconciliations')
    op.drop_index(op.f('ix_tds_payment_reconciliations_tds_challan_id'), table_name='tds_payment_reconciliations')
    op.drop_index(op.f('ix_tds_payment_reconciliations_status'), table_name='tds_payment_reconciliations')
    op.drop_index(op.f('ix_tds_payment_reconciliations_financial_year_id'), table_name='tds_payment_reconciliations')
    op.drop_index(op.f('ix_tds_payment_reconciliations_company_id'), table_name='tds_payment_reconciliations')
    op.drop_index('ix_tds_payment_reconciliations_company_fy', table_name='tds_payment_reconciliations')
    op.drop_table('tds_payment_reconciliations')
    # ### end Alembic commands ###
