"""add gstr2b import support

Revision ID: 67969da348ac
Revises: 96e14213de51
Create Date: 2026-09-15 17:28:35.150490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.types


# revision identifiers, used by Alembic.
revision: str = '67969da348ac'
down_revision: Union[str, None] = '96e14213de51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_jobs', sa.Column('return_period_id', app.utils.types.GUID(), nullable=True))
    op.create_foreign_key(None, 'import_jobs', 'gst_return_periods', ['return_period_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'import_jobs', type_='foreignkey')
    op.drop_column('import_jobs', 'return_period_id')
    # ### end Alembic commands ###
