"""add_tds_foundation_tables

Revision ID: 6b98c35e3d5c
Revises: 67969da348ac
Create Date: 2026-09-16 15:58:53.594811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.types


# revision identifiers, used by Alembic.
revision: str = '6b98c35e3d5c'
down_revision: Union[str, None] = '67969da348ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tds_sections',
    sa.Column('section_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('payment_nature', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tds_sections_code_unique', 'tds_sections', ['section_code'], unique=True)
    op.create_table('tds_profiles',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('tan', sa.String(length=10), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('deductor_type', sa.Enum('COMPANY', 'INDIVIDUAL', 'HUF', 'FIRM', 'LLP', 'GOVERNMENT', 'TRUST', 'OTHER', name='deductortype', native_enum=False, length=15), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('state_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='tdsprofilestatus', native_enum=False, length=10), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tds_profiles_company_id'), 'tds_profiles', ['company_id'], unique=False)
    op.create_index('ix_tds_profiles_company_unique', 'tds_profiles', ['company_id'], unique=True)
    op.create_index(op.f('ix_tds_profiles_tan'), 'tds_profiles', ['tan'], unique=False)
    op.create_table('tds_rules',
    sa.Column('tds_section_id', app.utils.types.GUID(), nullable=False),
    sa.Column('company_id', app.utils.types.GUID(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rate_type', sa.Enum('PERCENTAGE', 'FIXED', name='tdsratetype', native_enum=False), nullable=False),
    sa.Column('no_pan_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('threshold_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('aggregate_threshold_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('deductee_type', sa.Enum('INDIVIDUAL', 'COMPANY', 'FIRM', 'LLP', 'TRUST', 'HUF', 'OTHER', name='deducteetype', native_enum=False, length=15), nullable=True),
    sa.Column('pan_required', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('special_condition', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tds_section_id'], ['tds_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tds_rules_company_id'), 'tds_rules', ['company_id'], unique=False)
    op.create_index('ix_tds_rules_section_company', 'tds_rules', ['tds_section_id', 'company_id'], unique=False)
    op.create_index(op.f('ix_tds_rules_tds_section_id'), 'tds_rules', ['tds_section_id'], unique=False)
    op.create_table('deductees',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('vendor_id', app.utils.types.GUID(), nullable=True),
    sa.Column('customer_id', app.utils.types.GUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('pan', sa.String(length=10), nullable=True),
    sa.Column('pan_status', sa.Enum('AVAILABLE', 'NOT_AVAILABLE', 'INVALID', 'PENDING_REVIEW', name='panstatus', native_enum=False, length=15), nullable=False),
    sa.Column('deductee_type', sa.Enum('INDIVIDUAL', 'COMPANY', 'FIRM', 'LLP', 'TRUST', 'HUF', 'OTHER', name='deducteetype', native_enum=False, length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deductees_company_code', 'deductees', ['company_id', 'code'], unique=True)
    op.create_index(op.f('ix_deductees_company_id'), 'deductees', ['company_id'], unique=False)
    op.create_index(op.f('ix_deductees_customer_id'), 'deductees', ['customer_id'], unique=False)
    op.create_index(op.f('ix_deductees_pan'), 'deductees', ['pan'], unique=False)
    op.create_index(op.f('ix_deductees_vendor_id'), 'deductees', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deductees_vendor_id'), table_name='deductees')
    op.drop_index(op.f('ix_deductees_pan'), table_name='deductees')
    op.drop_index(op.f('ix_deductees_customer_id'), table_name='deductees')
    op.drop_index(op.f('ix_deductees_company_id'), table_name='deductees')
    op.drop_index('ix_deductees_company_code', table_name='deductees')
    op.drop_table('deductees')
    op.drop_index(op.f('ix_tds_rules_tds_section_id'), table_name='tds_rules')
    op.drop_index('ix_tds_rules_section_company', table_name='tds_rules')
    op.drop_index(op.f('ix_tds_rules_company_id'), table_name='tds_rules')
    op.drop_table('tds_rules')
    op.drop_index(op.f('ix_tds_profiles_tan'), table_name='tds_profiles')
    op.drop_index('ix_tds_profiles_company_unique', table_name='tds_profiles')
    op.drop_index(op.f('ix_tds_profiles_company_id'), table_name='tds_profiles')
    op.drop_table('tds_profiles')
    op.drop_index('ix_tds_sections_code_unique', table_name='tds_sections')
    op.drop_table('tds_sections')
    # ### end Alembic commands ###
