"""phase7 audit workflow engagements findings

Revision ID: 727a0310a24f
Revises: 0324bbd7f4ef
Create Date: 2026-09-18 13:07:27.567825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.types


# revision identifiers, used by Alembic.
revision: str = '727a0310a24f'
down_revision: Union[str, None] = '0324bbd7f4ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_engagements',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('engagement_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('engagement_type', sa.Enum('INTERNAL_REVIEW', 'TAX_COMPLIANCE_REVIEW', 'FINANCIAL_REVIEW', 'BOOKS_REVIEW', 'PRE_AUDIT_REVIEW', 'GENERAL_AUDIT', 'OTHER', name='auditengagementtype', native_enum=False, length=25), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'ASSIGNED', 'IN_REVIEW', 'PENDING_CLIENT_ACTION', 'PENDING_AUDITOR_REVIEW', 'APPROVED', 'SIGNED_OFF', 'CLOSED', 'CANCELLED', name='auditengagementstatus', native_enum=False, length=25), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', app.utils.types.GUID(), nullable=True),
    sa.Column('created_by', app.utils.types.GUID(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_engagements_company_code', 'audit_engagements', ['company_id', 'engagement_code'], unique=True)
    op.create_index(op.f('ix_audit_engagements_company_id'), 'audit_engagements', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_engagements_financial_year_id'), 'audit_engagements', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_audit_engagements_status'), 'audit_engagements', ['status'], unique=False)
    op.create_table('audit_assignments',
    sa.Column('engagement_id', app.utils.types.GUID(), nullable=False),
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('user_id', app.utils.types.GUID(), nullable=False),
    sa.Column('role', sa.Enum('LEAD_AUDITOR', 'AUDITOR', 'REVIEWER', 'ACCOUNTANT', 'CLIENT_CONTACT', name='auditassignmentrole', native_enum=False, length=20), nullable=False),
    sa.Column('assigned_by', app.utils.types.GUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['engagement_id'], ['audit_engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_assignments_company_id'), 'audit_assignments', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_assignments_engagement_id'), 'audit_assignments', ['engagement_id'], unique=False)
    op.create_index('ix_audit_assignments_unique_active', 'audit_assignments', ['engagement_id', 'user_id', 'role'], unique=True, postgresql_where='is_active = true', sqlite_where='is_active = 1')
    op.create_index(op.f('ix_audit_assignments_user_id'), 'audit_assignments', ['user_id'], unique=False)
    op.create_table('audit_checklists',
    sa.Column('engagement_id', app.utils.types.GUID(), nullable=False),
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['engagement_id'], ['audit_engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_checklists_company_id'), 'audit_checklists', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_checklists_engagement_id'), 'audit_checklists', ['engagement_id'], unique=False)
    op.create_index('ix_audit_checklists_engagement_unique', 'audit_checklists', ['engagement_id'], unique=True)
    op.create_table('audit_findings',
    sa.Column('engagement_id', app.utils.types.GUID(), nullable=False),
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('finding_code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('ACCOUNTING', 'GST', 'TDS', 'BANK', 'DOCUMENT', 'DATA_QUALITY', 'CONTROL', 'COMPLIANCE', 'PROCESS', 'OTHER', name='auditfindingcategory', native_enum=False, length=20), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='auditfindingseverity', native_enum=False, length=10), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ASSIGNED', 'IN_REVIEW', 'ACTION_REQUIRED', 'RESPONSE_SUBMITTED', 'RESOLVED', 'REOPENED', 'CLOSED', 'REJECTED', name='auditfindingstatus', native_enum=False, length=20), nullable=False),
    sa.Column('source_type', sa.Enum('DOCUMENT', 'SALES_INVOICE', 'PURCHASE_INVOICE', 'PAYMENT', 'RECEIPT', 'JOURNAL_ENTRY', 'GST_RETURN_PERIOD', 'GSTR2B_RECORD', 'TDS_TRANSACTION', 'TDS_CHALLAN', 'BANK_TRANSACTION', 'BANK_RECONCILIATION', 'OTHER', name='auditfindingsourcetype', native_enum=False, length=20), nullable=True),
    sa.Column('source_id', app.utils.types.GUID(), nullable=True),
    sa.Column('assigned_to', app.utils.types.GUID(), nullable=True),
    sa.Column('created_by', app.utils.types.GUID(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['engagement_id'], ['audit_engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_findings_assigned_to'), 'audit_findings', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_audit_findings_category'), 'audit_findings', ['category'], unique=False)
    op.create_index(op.f('ix_audit_findings_company_id'), 'audit_findings', ['company_id'], unique=False)
    op.create_index('ix_audit_findings_company_status', 'audit_findings', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_audit_findings_due_date'), 'audit_findings', ['due_date'], unique=False)
    op.create_index('ix_audit_findings_engagement_code', 'audit_findings', ['engagement_id', 'finding_code'], unique=True)
    op.create_index(op.f('ix_audit_findings_engagement_id'), 'audit_findings', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_audit_findings_severity'), 'audit_findings', ['severity'], unique=False)
    op.create_index('ix_audit_findings_source', 'audit_findings', ['source_type', 'source_id'], unique=False)
    op.create_index(op.f('ix_audit_findings_status'), 'audit_findings', ['status'], unique=False)
    op.create_table('audit_reviews',
    sa.Column('engagement_id', app.utils.types.GUID(), nullable=False),
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('reviewer_id', app.utils.types.GUID(), nullable=False),
    sa.Column('review_type', sa.Enum('INITIAL_REVIEW', 'FINAL_REVIEW', 'SECOND_REVIEW', 'QUALITY_REVIEW', name='auditreviewtype', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'RETURNED', name='auditreviewstatus', native_enum=False, length=15), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['engagement_id'], ['audit_engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_reviews_company_id'), 'audit_reviews', ['company_id'], unique=False)
    op.create_index('ix_audit_reviews_engagement', 'audit_reviews', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_audit_reviews_engagement_id'), 'audit_reviews', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_audit_reviews_status'), 'audit_reviews', ['status'], unique=False)
    op.create_table('audit_signoffs',
    sa.Column('engagement_id', app.utils.types.GUID(), nullable=False),
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('signed_by', app.utils.types.GUID(), nullable=False),
    sa.Column('sign_off_type', sa.Enum('LEAD_AUDITOR', 'REVIEWER', 'COMPANY_ACKNOWLEDGEMENT', name='auditsignofftype', native_enum=False, length=25), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['engagement_id'], ['audit_engagements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_signoffs_company_id'), 'audit_signoffs', ['company_id'], unique=False)
    op.create_index('ix_audit_signoffs_engagement', 'audit_signoffs', ['engagement_id'], unique=False)
    op.create_index(op.f('ix_audit_signoffs_engagement_id'), 'audit_signoffs', ['engagement_id'], unique=False)
    op.create_table('audit_checklist_items',
    sa.Column('checklist_id', app.utils.types.GUID(), nullable=False),
    sa.Column('engagement_id', app.utils.types.GUID(), nullable=False),
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('category', sa.Enum('ACCOUNTING', 'GST', 'TDS', 'BANK', 'DOCUMENTS', 'INTERNAL_CONTROLS', 'OTHER', name='auditchecklistcategory', native_enum=False, length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'NOT_APPLICABLE', 'REQUIRES_ATTENTION', name='auditchecklistitemstatus', native_enum=False, length=20), nullable=False),
    sa.Column('assigned_to', app.utils.types.GUID(), nullable=True),
    sa.Column('completed_by', app.utils.types.GUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['checklist_id'], ['audit_checklists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['engagement_id'], ['audit_engagements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_checklist_items_category'), 'audit_checklist_items', ['category'], unique=False)
    op.create_index(op.f('ix_audit_checklist_items_checklist_id'), 'audit_checklist_items', ['checklist_id'], unique=False)
    op.create_index(op.f('ix_audit_checklist_items_company_id'), 'audit_checklist_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_checklist_items_engagement_id'), 'audit_checklist_items', ['engagement_id'], unique=False)
    op.create_index('ix_audit_checklist_items_engagement_status', 'audit_checklist_items', ['engagement_id', 'status'], unique=False)
    op.create_index(op.f('ix_audit_checklist_items_status'), 'audit_checklist_items', ['status'], unique=False)
    op.create_table('audit_finding_comments',
    sa.Column('finding_id', app.utils.types.GUID(), nullable=False),
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('user_id', app.utils.types.GUID(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['audit_findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_finding_comments_company_id'), 'audit_finding_comments', ['company_id'], unique=False)
    op.create_index('ix_audit_finding_comments_finding', 'audit_finding_comments', ['finding_id'], unique=False)
    op.create_index(op.f('ix_audit_finding_comments_finding_id'), 'audit_finding_comments', ['finding_id'], unique=False)
    op.create_table('audit_finding_evidence',
    sa.Column('finding_id', app.utils.types.GUID(), nullable=False),
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('document_id', app.utils.types.GUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('added_by', app.utils.types.GUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['finding_id'], ['audit_findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_finding_evidence_company_id'), 'audit_finding_evidence', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_finding_evidence_document_id'), 'audit_finding_evidence', ['document_id'], unique=False)
    op.create_index('ix_audit_finding_evidence_finding', 'audit_finding_evidence', ['finding_id'], unique=False)
    op.create_index(op.f('ix_audit_finding_evidence_finding_id'), 'audit_finding_evidence', ['finding_id'], unique=False)
    op.create_table('audit_finding_responses',
    sa.Column('finding_id', app.utils.types.GUID(), nullable=False),
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('submitted_by', app.utils.types.GUID(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'ACCEPTED', 'REJECTED', name='auditfindingresponsestatus', native_enum=False, length=10), nullable=False),
    sa.Column('reviewed_by', app.utils.types.GUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['audit_findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_finding_responses_company_id'), 'audit_finding_responses', ['company_id'], unique=False)
    op.create_index('ix_audit_finding_responses_finding', 'audit_finding_responses', ['finding_id'], unique=False)
    op.create_index(op.f('ix_audit_finding_responses_finding_id'), 'audit_finding_responses', ['finding_id'], unique=False)
    op.create_index(op.f('ix_audit_finding_responses_status'), 'audit_finding_responses', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_finding_responses_status'), table_name='audit_finding_responses')
    op.drop_index(op.f('ix_audit_finding_responses_finding_id'), table_name='audit_finding_responses')
    op.drop_index('ix_audit_finding_responses_finding', table_name='audit_finding_responses')
    op.drop_index(op.f('ix_audit_finding_responses_company_id'), table_name='audit_finding_responses')
    op.drop_table('audit_finding_responses')
    op.drop_index(op.f('ix_audit_finding_evidence_finding_id'), table_name='audit_finding_evidence')
    op.drop_index('ix_audit_finding_evidence_finding', table_name='audit_finding_evidence')
    op.drop_index(op.f('ix_audit_finding_evidence_document_id'), table_name='audit_finding_evidence')
    op.drop_index(op.f('ix_audit_finding_evidence_company_id'), table_name='audit_finding_evidence')
    op.drop_table('audit_finding_evidence')
    op.drop_index(op.f('ix_audit_finding_comments_finding_id'), table_name='audit_finding_comments')
    op.drop_index('ix_audit_finding_comments_finding', table_name='audit_finding_comments')
    op.drop_index(op.f('ix_audit_finding_comments_company_id'), table_name='audit_finding_comments')
    op.drop_table('audit_finding_comments')
    op.drop_index(op.f('ix_audit_checklist_items_status'), table_name='audit_checklist_items')
    op.drop_index('ix_audit_checklist_items_engagement_status', table_name='audit_checklist_items')
    op.drop_index(op.f('ix_audit_checklist_items_engagement_id'), table_name='audit_checklist_items')
    op.drop_index(op.f('ix_audit_checklist_items_company_id'), table_name='audit_checklist_items')
    op.drop_index(op.f('ix_audit_checklist_items_checklist_id'), table_name='audit_checklist_items')
    op.drop_index(op.f('ix_audit_checklist_items_category'), table_name='audit_checklist_items')
    op.drop_table('audit_checklist_items')
    op.drop_index(op.f('ix_audit_signoffs_engagement_id'), table_name='audit_signoffs')
    op.drop_index('ix_audit_signoffs_engagement', table_name='audit_signoffs')
    op.drop_index(op.f('ix_audit_signoffs_company_id'), table_name='audit_signoffs')
    op.drop_table('audit_signoffs')
    op.drop_index(op.f('ix_audit_reviews_status'), table_name='audit_reviews')
    op.drop_index(op.f('ix_audit_reviews_engagement_id'), table_name='audit_reviews')
    op.drop_index('ix_audit_reviews_engagement', table_name='audit_reviews')
    op.drop_index(op.f('ix_audit_reviews_company_id'), table_name='audit_reviews')
    op.drop_table('audit_reviews')
    op.drop_index(op.f('ix_audit_findings_status'), table_name='audit_findings')
    op.drop_index('ix_audit_findings_source', table_name='audit_findings')
    op.drop_index(op.f('ix_audit_findings_severity'), table_name='audit_findings')
    op.drop_index(op.f('ix_audit_findings_engagement_id'), table_name='audit_findings')
    op.drop_index('ix_audit_findings_engagement_code', table_name='audit_findings')
    op.drop_index(op.f('ix_audit_findings_due_date'), table_name='audit_findings')
    op.drop_index('ix_audit_findings_company_status', table_name='audit_findings')
    op.drop_index(op.f('ix_audit_findings_company_id'), table_name='audit_findings')
    op.drop_index(op.f('ix_audit_findings_category'), table_name='audit_findings')
    op.drop_index(op.f('ix_audit_findings_assigned_to'), table_name='audit_findings')
    op.drop_table('audit_findings')
    op.drop_index('ix_audit_checklists_engagement_unique', table_name='audit_checklists')
    op.drop_index(op.f('ix_audit_checklists_engagement_id'), table_name='audit_checklists')
    op.drop_index(op.f('ix_audit_checklists_company_id'), table_name='audit_checklists')
    op.drop_table('audit_checklists')
    op.drop_index(op.f('ix_audit_assignments_user_id'), table_name='audit_assignments')
    op.drop_index('ix_audit_assignments_unique_active', table_name='audit_assignments', postgresql_where='is_active = true', sqlite_where='is_active = 1')
    op.drop_index(op.f('ix_audit_assignments_engagement_id'), table_name='audit_assignments')
    op.drop_index(op.f('ix_audit_assignments_company_id'), table_name='audit_assignments')
    op.drop_table('audit_assignments')
    op.drop_index(op.f('ix_audit_engagements_status'), table_name='audit_engagements')
    op.drop_index(op.f('ix_audit_engagements_financial_year_id'), table_name='audit_engagements')
    op.drop_index(op.f('ix_audit_engagements_company_id'), table_name='audit_engagements')
    op.drop_index('ix_audit_engagements_company_code', table_name='audit_engagements')
    op.drop_table('audit_engagements')
    # ### end Alembic commands ###
