"""add gst compliance foundation tables

Revision ID: 96e14213de51
Revises: 353108526d88
Create Date: 2026-09-15 17:15:03.493646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.types


# revision identifiers, used by Alembic.
revision: str = '96e14213de51'
down_revision: Union[str, None] = '353108526d88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gst_profiles',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('gstin', sa.String(length=15), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('registration_type', sa.Enum('REGULAR', 'COMPOSITION', 'CASUAL', 'SEZ', 'OTHER', name='gstregistrationtype', native_enum=False, length=15), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('state_name', sa.String(length=100), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gst_profiles_company_id'), 'gst_profiles', ['company_id'], unique=False)
    op.create_index('ix_gst_profiles_company_unique', 'gst_profiles', ['company_id'], unique=True)
    op.create_index(op.f('ix_gst_profiles_gstin'), 'gst_profiles', ['gstin'], unique=False)
    op.create_table('gst_tax_rates',
    sa.Column('company_id', app.utils.types.GUID(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gst_tax_rates_company_id'), 'gst_tax_rates', ['company_id'], unique=False)
    op.create_index('ix_gst_tax_rates_company_rate', 'gst_tax_rates', ['company_id', 'rate'], unique=False)
    op.create_table('gst_return_periods',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'FINALIZED', 'ARCHIVED', name='gstreturnperiodstatus', native_enum=False, length=15), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('month >= 1 AND month <= 12', name='ck_gst_return_periods_month_range'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gst_return_periods_company_id'), 'gst_return_periods', ['company_id'], unique=False)
    op.create_index(op.f('ix_gst_return_periods_financial_year_id'), 'gst_return_periods', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_gst_return_periods_status'), 'gst_return_periods', ['status'], unique=False)
    op.create_index('ix_gst_return_periods_unique', 'gst_return_periods', ['company_id', 'year', 'month'], unique=True)
    op.create_table('gst_reconciliations',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('return_period_id', app.utils.types.GUID(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_by', app.utils.types.GUID(), nullable=False),
    sa.Column('total_purchase_invoices', sa.Integer(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('partially_matched_count', sa.Integer(), nullable=False),
    sa.Column('mismatch_count', sa.Integer(), nullable=False),
    sa.Column('books_only_count', sa.Integer(), nullable=False),
    sa.Column('gstr2b_only_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('review_required_count', sa.Integer(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['return_period_id'], ['gst_return_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gst_reconciliations_company_id'), 'gst_reconciliations', ['company_id'], unique=False)
    op.create_index(op.f('ix_gst_reconciliations_return_period_id'), 'gst_reconciliations', ['return_period_id'], unique=False)
    op.create_table('gst_return_snapshots',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('return_period_id', app.utils.types.GUID(), nullable=False),
    sa.Column('return_type', sa.Enum('GSTR1', 'GSTR3B', name='gstreturntype', native_enum=False, length=10), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'UNDER_REVIEW', 'CHANGES_REQUESTED', 'APPROVED', 'FINALIZED', name='gstreturnsnapshotstatus', native_enum=False, length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_by', app.utils.types.GUID(), nullable=True),
    sa.Column('summary_data', sa.JSON(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['return_period_id'], ['gst_return_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gst_return_snapshots_company_id'), 'gst_return_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_gst_return_snapshots_return_period_id'), 'gst_return_snapshots', ['return_period_id'], unique=False)
    op.create_index(op.f('ix_gst_return_snapshots_return_type'), 'gst_return_snapshots', ['return_type'], unique=False)
    op.create_index(op.f('ix_gst_return_snapshots_status'), 'gst_return_snapshots', ['status'], unique=False)
    op.create_index('ix_gst_return_snapshots_unique_version', 'gst_return_snapshots', ['return_period_id', 'return_type', 'version'], unique=True)
    op.create_table('gst_review_notes',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('return_period_id', app.utils.types.GUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='gstreviewnotestatus', native_enum=False, length=10), nullable=False),
    sa.Column('created_by', app.utils.types.GUID(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['return_period_id'], ['gst_return_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gst_review_notes_company_id'), 'gst_review_notes', ['company_id'], unique=False)
    op.create_index('ix_gst_review_notes_entity', 'gst_review_notes', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_gst_review_notes_return_period_id'), 'gst_review_notes', ['return_period_id'], unique=False)
    op.create_index(op.f('ix_gst_review_notes_status'), 'gst_review_notes', ['status'], unique=False)
    op.create_table('gstr2b_records',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('return_period_id', app.utils.types.GUID(), nullable=False),
    sa.Column('import_job_id', app.utils.types.GUID(), nullable=True),
    sa.Column('supplier_gstin', sa.String(length=15), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('document_type', sa.Enum('INVOICE', 'CREDIT_NOTE', 'DEBIT_NOTE', name='gstr2bdocumenttype', native_enum=False, length=15), nullable=False),
    sa.Column('taxable_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cess_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['return_period_id'], ['gst_return_periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gstr2b_records_company_id'), 'gstr2b_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_gstr2b_records_invoice_number'), 'gstr2b_records', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_gstr2b_records_return_period_id'), 'gstr2b_records', ['return_period_id'], unique=False)
    op.create_index(op.f('ix_gstr2b_records_supplier_gstin'), 'gstr2b_records', ['supplier_gstin'], unique=False)
    op.create_index('ix_gstr2b_records_supplier_invoice', 'gstr2b_records', ['company_id', 'return_period_id', 'supplier_gstin', 'invoice_number'], unique=False)
    op.create_table('gst_reconciliation_results',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('reconciliation_id', app.utils.types.GUID(), nullable=False),
    sa.Column('purchase_invoice_id', app.utils.types.GUID(), nullable=True),
    sa.Column('gstr2b_record_id', app.utils.types.GUID(), nullable=True),
    sa.Column('status', sa.Enum('MATCHED', 'PARTIALLY_MATCHED', 'AMOUNT_MISMATCH', 'DATE_MISMATCH', 'GSTIN_MISMATCH', 'INVOICE_NUMBER_MISMATCH', 'BOOKS_ONLY', 'GSTR2B_ONLY', 'DUPLICATE', 'REVIEW_REQUIRED', name='reconciliationstatus', native_enum=False, length=30), nullable=False),
    sa.Column('books_taxable_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('books_cgst_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('books_sgst_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('books_igst_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('books_cess_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('gstr2b_taxable_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('gstr2b_cgst_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('gstr2b_sgst_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('gstr2b_igst_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('gstr2b_cess_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('taxable_value_diff', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_diff', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('itc_category', sa.Enum('MATCHED_ITC', 'UNMATCHED_ITC', 'POTENTIAL_ITC', 'REVIEW_REQUIRED', 'INELIGIBLE', name='itccategory', native_enum=False, length=20), nullable=True),
    sa.Column('itc_review_status', sa.Enum('PENDING', 'REVIEWED', 'ACCEPTED', 'REJECTED', name='itcreviewstatus', native_enum=False, length=15), nullable=False),
    sa.Column('reviewed_by', app.utils.types.GUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.String(length=500), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gstr2b_record_id'], ['gstr2b_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_invoice_id'], ['purchase_invoices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reconciliation_id'], ['gst_reconciliations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gst_reconciliation_results_company_id'), 'gst_reconciliation_results', ['company_id'], unique=False)
    op.create_index(op.f('ix_gst_reconciliation_results_itc_category'), 'gst_reconciliation_results', ['itc_category'], unique=False)
    op.create_index('ix_gst_reconciliation_results_reconciliation', 'gst_reconciliation_results', ['reconciliation_id', 'status'], unique=False)
    op.create_index(op.f('ix_gst_reconciliation_results_reconciliation_id'), 'gst_reconciliation_results', ['reconciliation_id'], unique=False)
    op.create_index(op.f('ix_gst_reconciliation_results_status'), 'gst_reconciliation_results', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gst_reconciliation_results_status'), table_name='gst_reconciliation_results')
    op.drop_index(op.f('ix_gst_reconciliation_results_reconciliation_id'), table_name='gst_reconciliation_results')
    op.drop_index('ix_gst_reconciliation_results_reconciliation', table_name='gst_reconciliation_results')
    op.drop_index(op.f('ix_gst_reconciliation_results_itc_category'), table_name='gst_reconciliation_results')
    op.drop_index(op.f('ix_gst_reconciliation_results_company_id'), table_name='gst_reconciliation_results')
    op.drop_table('gst_reconciliation_results')
    op.drop_index('ix_gstr2b_records_supplier_invoice', table_name='gstr2b_records')
    op.drop_index(op.f('ix_gstr2b_records_supplier_gstin'), table_name='gstr2b_records')
    op.drop_index(op.f('ix_gstr2b_records_return_period_id'), table_name='gstr2b_records')
    op.drop_index(op.f('ix_gstr2b_records_invoice_number'), table_name='gstr2b_records')
    op.drop_index(op.f('ix_gstr2b_records_company_id'), table_name='gstr2b_records')
    op.drop_table('gstr2b_records')
    op.drop_index(op.f('ix_gst_review_notes_status'), table_name='gst_review_notes')
    op.drop_index(op.f('ix_gst_review_notes_return_period_id'), table_name='gst_review_notes')
    op.drop_index('ix_gst_review_notes_entity', table_name='gst_review_notes')
    op.drop_index(op.f('ix_gst_review_notes_company_id'), table_name='gst_review_notes')
    op.drop_table('gst_review_notes')
    op.drop_index('ix_gst_return_snapshots_unique_version', table_name='gst_return_snapshots')
    op.drop_index(op.f('ix_gst_return_snapshots_status'), table_name='gst_return_snapshots')
    op.drop_index(op.f('ix_gst_return_snapshots_return_type'), table_name='gst_return_snapshots')
    op.drop_index(op.f('ix_gst_return_snapshots_return_period_id'), table_name='gst_return_snapshots')
    op.drop_index(op.f('ix_gst_return_snapshots_company_id'), table_name='gst_return_snapshots')
    op.drop_table('gst_return_snapshots')
    op.drop_index(op.f('ix_gst_reconciliations_return_period_id'), table_name='gst_reconciliations')
    op.drop_index(op.f('ix_gst_reconciliations_company_id'), table_name='gst_reconciliations')
    op.drop_table('gst_reconciliations')
    op.drop_index('ix_gst_return_periods_unique', table_name='gst_return_periods')
    op.drop_index(op.f('ix_gst_return_periods_status'), table_name='gst_return_periods')
    op.drop_index(op.f('ix_gst_return_periods_financial_year_id'), table_name='gst_return_periods')
    op.drop_index(op.f('ix_gst_return_periods_company_id'), table_name='gst_return_periods')
    op.drop_table('gst_return_periods')
    op.drop_index('ix_gst_tax_rates_company_rate', table_name='gst_tax_rates')
    op.drop_index(op.f('ix_gst_tax_rates_company_id'), table_name='gst_tax_rates')
    op.drop_table('gst_tax_rates')
    op.drop_index(op.f('ix_gst_profiles_gstin'), table_name='gst_profiles')
    op.drop_index('ix_gst_profiles_company_unique', table_name='gst_profiles')
    op.drop_index(op.f('ix_gst_profiles_company_id'), table_name='gst_profiles')
    op.drop_table('gst_profiles')
    # ### end Alembic commands ###
