"""phase9 compliance calendar task management notifications

Revision ID: 9f0530640b44
Revises: a688543c3a32
Create Date: 2026-09-19 12:51:00.141920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.types


# revision identifiers, used by Alembic.
revision: str = '9f0530640b44'
down_revision: Union[str, None] = 'a688543c3a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_rules',
    sa.Column('company_id', app.utils.types.GUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('GST', 'TDS', 'INCOME_TAX', 'AUDIT', 'ACCOUNTING', 'BANK', 'GENERAL', 'OTHER', name='compliancecategory', native_enum=False, length=15), nullable=False),
    sa.Column('module', sa.Enum('GST', 'TDS', 'INCOME_TAX', 'AUDIT', 'BANK_RECONCILIATION', 'ACCOUNTING', 'DOCUMENTS', 'GENERAL', name='compliancemodule', native_enum=False, length=25), nullable=False),
    sa.Column('frequency', sa.Enum('MONTHLY', 'QUARTERLY', 'ANNUAL', 'ONE_TIME', 'CUSTOM', name='compliancefrequency', native_enum=False, length=10), nullable=False),
    sa.Column('due_date_rule', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='compliancepriority', native_enum=False, length=10), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_rules_category'), 'compliance_rules', ['category'], unique=False)
    op.create_index(op.f('ix_compliance_rules_code'), 'compliance_rules', ['code'], unique=False)
    op.create_index(op.f('ix_compliance_rules_company_id'), 'compliance_rules', ['company_id'], unique=False)
    op.create_index(op.f('ix_compliance_rules_module'), 'compliance_rules', ['module'], unique=False)
    op.create_index('ix_compliance_rules_unique_version', 'compliance_rules', ['code', 'company_id', 'version'], unique=True)
    op.create_table('notifications',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('user_id', app.utils.types.GUID(), nullable=False),
    sa.Column('type', sa.Enum('TASK_ASSIGNED', 'TASK_DUE_SOON', 'TASK_OVERDUE', 'TASK_REVIEW_REQUIRED', 'TASK_COMPLETED', 'TASK_VERIFIED', 'COMMENT_ADDED', 'TASK_REASSIGNED', name='notificationtype', native_enum=False, length=25), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='notificationseverity', native_enum=False, length=10), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', app.utils.types.GUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_company_id'), 'notifications', ['company_id'], unique=False)
    op.create_index('ix_notifications_company_user', 'notifications', ['company_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('compliance_obligations',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('GST', 'TDS', 'INCOME_TAX', 'AUDIT', 'ACCOUNTING', 'BANK', 'GENERAL', 'OTHER', name='compliancecategory', native_enum=False, length=15), nullable=False),
    sa.Column('module', sa.Enum('GST', 'TDS', 'INCOME_TAX', 'AUDIT', 'BANK_RECONCILIATION', 'ACCOUNTING', 'DOCUMENTS', 'GENERAL', name='compliancemodule', native_enum=False, length=25), nullable=False),
    sa.Column('frequency', sa.Enum('MONTHLY', 'QUARTERLY', 'ANNUAL', 'ONE_TIME', 'CUSTOM', name='compliancefrequency', native_enum=False, length=10), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=True),
    sa.Column('tax_period', sa.String(length=20), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('grace_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='compliancepriority', native_enum=False, length=10), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FULFILLED', 'CANCELLED', name='complianceobligationstatus', native_enum=False, length=15), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('rule_id', app.utils.types.GUID(), nullable=True),
    sa.Column('rule_version', sa.Integer(), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', app.utils.types.GUID(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_id'], ['compliance_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_obligations_category'), 'compliance_obligations', ['category'], unique=False)
    op.create_index(op.f('ix_compliance_obligations_company_id'), 'compliance_obligations', ['company_id'], unique=False)
    op.create_index(op.f('ix_compliance_obligations_due_date'), 'compliance_obligations', ['due_date'], unique=False)
    op.create_index(op.f('ix_compliance_obligations_financial_year_id'), 'compliance_obligations', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_compliance_obligations_module'), 'compliance_obligations', ['module'], unique=False)
    op.create_index(op.f('ix_compliance_obligations_status'), 'compliance_obligations', ['status'], unique=False)
    op.create_index('ix_compliance_obligations_unique', 'compliance_obligations', ['company_id', 'code', 'financial_year_id', 'tax_period'], unique=True)
    op.create_table('compliance_tasks',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('obligation_id', app.utils.types.GUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('GST', 'TDS', 'INCOME_TAX', 'AUDIT', 'ACCOUNTING', 'BANK', 'GENERAL', 'OTHER', name='compliancecategory', native_enum=False, length=15), nullable=False),
    sa.Column('module', sa.Enum('GST', 'TDS', 'INCOME_TAX', 'AUDIT', 'BANK_RECONCILIATION', 'ACCOUNTING', 'DOCUMENTS', 'GENERAL', name='compliancemodule', native_enum=False, length=25), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'PENDING_REVIEW', 'COMPLETED', 'VERIFIED', 'OVERDUE', 'CANCELLED', 'LOCKED', name='compliancetaskstatus', native_enum=False, length=15), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='compliancepriority', native_enum=False, length=10), nullable=False),
    sa.Column('assigned_to', app.utils.types.GUID(), nullable=True),
    sa.Column('reviewer_id', app.utils.types.GUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_type', sa.Enum('GST_RETURN', 'TDS_RETURN', 'INCOME_TAX_RETURN', 'AUDIT_ENGAGEMENT', 'AUDIT_CHECKLIST', 'BANK_RECONCILIATION', 'ACCOUNTING_PERIOD', 'DOCUMENT', 'MANUAL', name='compliancesourcetype', native_enum=False, length=20), nullable=False),
    sa.Column('source_id', app.utils.types.GUID(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('created_by', app.utils.types.GUID(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['obligation_id'], ['compliance_obligations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_tasks_assigned_to'), 'compliance_tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_compliance_tasks_category'), 'compliance_tasks', ['category'], unique=False)
    op.create_index('ix_compliance_tasks_company_due_date', 'compliance_tasks', ['company_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_compliance_tasks_company_id'), 'compliance_tasks', ['company_id'], unique=False)
    op.create_index('ix_compliance_tasks_company_status', 'compliance_tasks', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_compliance_tasks_due_date'), 'compliance_tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_compliance_tasks_module'), 'compliance_tasks', ['module'], unique=False)
    op.create_index(op.f('ix_compliance_tasks_obligation_id'), 'compliance_tasks', ['obligation_id'], unique=False)
    op.create_index(op.f('ix_compliance_tasks_priority'), 'compliance_tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_compliance_tasks_reviewer_id'), 'compliance_tasks', ['reviewer_id'], unique=False)
    op.create_index('ix_compliance_tasks_source', 'compliance_tasks', ['source_type', 'source_id'], unique=False)
    op.create_index(op.f('ix_compliance_tasks_status'), 'compliance_tasks', ['status'], unique=False)
    op.create_table('compliance_task_comments',
    sa.Column('task_id', app.utils.types.GUID(), nullable=False),
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('user_id', app.utils.types.GUID(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['compliance_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_task_comments_company_id'), 'compliance_task_comments', ['company_id'], unique=False)
    op.create_index('ix_compliance_task_comments_task', 'compliance_task_comments', ['task_id'], unique=False)
    op.create_index(op.f('ix_compliance_task_comments_task_id'), 'compliance_task_comments', ['task_id'], unique=False)
    op.create_table('compliance_task_evidence',
    sa.Column('task_id', app.utils.types.GUID(), nullable=False),
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('document_id', app.utils.types.GUID(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_by', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['compliance_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_task_evidence_company_id'), 'compliance_task_evidence', ['company_id'], unique=False)
    op.create_index(op.f('ix_compliance_task_evidence_document_id'), 'compliance_task_evidence', ['document_id'], unique=False)
    op.create_index('ix_compliance_task_evidence_task', 'compliance_task_evidence', ['task_id'], unique=False)
    op.create_index(op.f('ix_compliance_task_evidence_task_id'), 'compliance_task_evidence', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_task_evidence_task_id'), table_name='compliance_task_evidence')
    op.drop_index('ix_compliance_task_evidence_task', table_name='compliance_task_evidence')
    op.drop_index(op.f('ix_compliance_task_evidence_document_id'), table_name='compliance_task_evidence')
    op.drop_index(op.f('ix_compliance_task_evidence_company_id'), table_name='compliance_task_evidence')
    op.drop_table('compliance_task_evidence')
    op.drop_index(op.f('ix_compliance_task_comments_task_id'), table_name='compliance_task_comments')
    op.drop_index('ix_compliance_task_comments_task', table_name='compliance_task_comments')
    op.drop_index(op.f('ix_compliance_task_comments_company_id'), table_name='compliance_task_comments')
    op.drop_table('compliance_task_comments')
    op.drop_index(op.f('ix_compliance_tasks_status'), table_name='compliance_tasks')
    op.drop_index('ix_compliance_tasks_source', table_name='compliance_tasks')
    op.drop_index(op.f('ix_compliance_tasks_reviewer_id'), table_name='compliance_tasks')
    op.drop_index(op.f('ix_compliance_tasks_priority'), table_name='compliance_tasks')
    op.drop_index(op.f('ix_compliance_tasks_obligation_id'), table_name='compliance_tasks')
    op.drop_index(op.f('ix_compliance_tasks_module'), table_name='compliance_tasks')
    op.drop_index(op.f('ix_compliance_tasks_due_date'), table_name='compliance_tasks')
    op.drop_index('ix_compliance_tasks_company_status', table_name='compliance_tasks')
    op.drop_index(op.f('ix_compliance_tasks_company_id'), table_name='compliance_tasks')
    op.drop_index('ix_compliance_tasks_company_due_date', table_name='compliance_tasks')
    op.drop_index(op.f('ix_compliance_tasks_category'), table_name='compliance_tasks')
    op.drop_index(op.f('ix_compliance_tasks_assigned_to'), table_name='compliance_tasks')
    op.drop_table('compliance_tasks')
    op.drop_index('ix_compliance_obligations_unique', table_name='compliance_obligations')
    op.drop_index(op.f('ix_compliance_obligations_status'), table_name='compliance_obligations')
    op.drop_index(op.f('ix_compliance_obligations_module'), table_name='compliance_obligations')
    op.drop_index(op.f('ix_compliance_obligations_financial_year_id'), table_name='compliance_obligations')
    op.drop_index(op.f('ix_compliance_obligations_due_date'), table_name='compliance_obligations')
    op.drop_index(op.f('ix_compliance_obligations_company_id'), table_name='compliance_obligations')
    op.drop_index(op.f('ix_compliance_obligations_category'), table_name='compliance_obligations')
    op.drop_table('compliance_obligations')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index('ix_notifications_company_user', table_name='notifications')
    op.drop_index(op.f('ix_notifications_company_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_compliance_rules_unique_version', table_name='compliance_rules')
    op.drop_index(op.f('ix_compliance_rules_module'), table_name='compliance_rules')
    op.drop_index(op.f('ix_compliance_rules_company_id'), table_name='compliance_rules')
    op.drop_index(op.f('ix_compliance_rules_code'), table_name='compliance_rules')
    op.drop_index(op.f('ix_compliance_rules_category'), table_name='compliance_rules')
    op.drop_table('compliance_rules')
    # ### end Alembic commands ###
