"""add_tds_challans

Revision ID: a47cccd57895
Revises: f9f81c3b679b
Create Date: 2026-09-18 10:06:57.822058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.types


# revision identifiers, used by Alembic.
revision: str = 'a47cccd57895'
down_revision: Union[str, None] = 'f9f81c3b679b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tds_challans',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('challan_number', sa.String(length=50), nullable=False),
    sa.Column('challan_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'PAID', 'RECONCILED', 'CANCELLED', name='tdschallanstatus', native_enum=False, length=15), nullable=False),
    sa.Column('bank_reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tds_challans_company_id'), 'tds_challans', ['company_id'], unique=False)
    op.create_index(op.f('ix_tds_challans_financial_year_id'), 'tds_challans', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_tds_challans_status'), 'tds_challans', ['status'], unique=False)
    op.create_index('ix_tds_challans_unique_number', 'tds_challans', ['company_id', 'financial_year_id', 'challan_number'], unique=True)
    op.create_table('tds_challan_allocations',
    sa.Column('challan_id', app.utils.types.GUID(), nullable=False),
    sa.Column('tds_transaction_id', app.utils.types.GUID(), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challan_id'], ['tds_challans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tds_transaction_id'], ['tds_transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tds_challan_allocations_challan', 'tds_challan_allocations', ['challan_id'], unique=False)
    op.create_index('ix_tds_challan_allocations_transaction', 'tds_challan_allocations', ['tds_transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tds_challan_allocations_transaction', table_name='tds_challan_allocations')
    op.drop_index('ix_tds_challan_allocations_challan', table_name='tds_challan_allocations')
    op.drop_table('tds_challan_allocations')
    op.drop_index('ix_tds_challans_unique_number', table_name='tds_challans')
    op.drop_index(op.f('ix_tds_challans_status'), table_name='tds_challans')
    op.drop_index(op.f('ix_tds_challans_financial_year_id'), table_name='tds_challans')
    op.drop_index(op.f('ix_tds_challans_company_id'), table_name='tds_challans')
    op.drop_table('tds_challans')
    # ### end Alembic commands ###
