"""phase8 income tax compliance engine

Revision ID: a688543c3a32
Revises: 727a0310a24f
Create Date: 2026-09-19 10:45:19.269932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.types


# revision identifiers, used by Alembic.
revision: str = 'a688543c3a32'
down_revision: Union[str, None] = '727a0310a24f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('income_tax_rule_sets',
    sa.Column('assessment_year', sa.String(length=10), nullable=False),
    sa.Column('taxpayer_type', sa.Enum('INDIVIDUAL', 'HUF', 'PARTNERSHIP', 'LLP', 'COMPANY', 'TRUST', 'OTHER', name='taxpayertype', native_enum=False, length=15), nullable=False),
    sa.Column('tax_regime', sa.Enum('OLD_REGIME', 'NEW_REGIME', name='taxregime', native_enum=False, length=15), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cess_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_tax_rule_sets_assessment_year'), 'income_tax_rule_sets', ['assessment_year'], unique=False)
    op.create_index(op.f('ix_income_tax_rule_sets_tax_regime'), 'income_tax_rule_sets', ['tax_regime'], unique=False)
    op.create_index(op.f('ix_income_tax_rule_sets_taxpayer_type'), 'income_tax_rule_sets', ['taxpayer_type'], unique=False)
    op.create_index('ix_income_tax_rule_sets_unique_version', 'income_tax_rule_sets', ['assessment_year', 'taxpayer_type', 'tax_regime', 'version'], unique=True)
    op.create_table('income_tax_deduction_rules',
    sa.Column('rule_set_id', app.utils.types.GUID(), nullable=False),
    sa.Column('section_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('allowed_in_old_regime', sa.Boolean(), nullable=False),
    sa.Column('allowed_in_new_regime', sa.Boolean(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['rule_set_id'], ['income_tax_rule_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_tax_deduction_rules_rule_set_id'), 'income_tax_deduction_rules', ['rule_set_id'], unique=False)
    op.create_index('ix_income_tax_deduction_rules_unique', 'income_tax_deduction_rules', ['rule_set_id', 'section_code'], unique=True)
    op.create_table('income_tax_profiles',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('pan', sa.String(length=10), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('trade_name', sa.String(length=255), nullable=True),
    sa.Column('taxpayer_type', sa.Enum('INDIVIDUAL', 'HUF', 'PARTNERSHIP', 'LLP', 'COMPANY', 'TRUST', 'OTHER', name='taxpayertype', native_enum=False, length=15), nullable=False),
    sa.Column('residential_status', sa.Enum('RESIDENT', 'RESIDENT_NOT_ORDINARILY_RESIDENT', 'NON_RESIDENT', name='residentialstatus', native_enum=False, length=35), nullable=False),
    sa.Column('date_of_birth_or_incorporation', sa.Date(), nullable=True),
    sa.Column('business_nature', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_tax_profiles_company_id'), 'income_tax_profiles', ['company_id'], unique=False)
    op.create_index('ix_income_tax_profiles_company_unique', 'income_tax_profiles', ['company_id'], unique=True)
    op.create_table('income_tax_rebate_rules',
    sa.Column('rule_set_id', app.utils.types.GUID(), nullable=False),
    sa.Column('maximum_income', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('maximum_rebate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['rule_set_id'], ['income_tax_rule_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_income_tax_rebate_rules_rule_set', 'income_tax_rebate_rules', ['rule_set_id'], unique=False)
    op.create_index(op.f('ix_income_tax_rebate_rules_rule_set_id'), 'income_tax_rebate_rules', ['rule_set_id'], unique=False)
    op.create_table('income_tax_slabs',
    sa.Column('rule_set_id', app.utils.types.GUID(), nullable=False),
    sa.Column('lower_limit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('upper_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['rule_set_id'], ['income_tax_rule_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_income_tax_slabs_rule_set', 'income_tax_slabs', ['rule_set_id'], unique=False)
    op.create_index(op.f('ix_income_tax_slabs_rule_set_id'), 'income_tax_slabs', ['rule_set_id'], unique=False)
    op.create_table('income_tax_surcharge_rules',
    sa.Column('rule_set_id', app.utils.types.GUID(), nullable=False),
    sa.Column('income_threshold', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['rule_set_id'], ['income_tax_rule_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_income_tax_surcharge_rules_rule_set', 'income_tax_surcharge_rules', ['rule_set_id'], unique=False)
    op.create_index(op.f('ix_income_tax_surcharge_rules_rule_set_id'), 'income_tax_surcharge_rules', ['rule_set_id'], unique=False)
    op.create_table('income_tax_adjustments',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('adjustment_type', sa.Enum('ADD_BACK', 'DEDUCTION', 'TIMING_DIFFERENCE', 'DEPRECIATION_ADJUSTMENT', 'OTHER', name='taxadjustmenttype', native_enum=False, length=25), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('book_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('difference', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source_type', sa.Enum('SALES_INVOICE', 'PURCHASE_INVOICE', 'PAYMENT', 'RECEIPT', 'JOURNAL_ENTRY', 'LEDGER', 'DOCUMENT', 'TDS_TRANSACTION', 'OTHER', name='incometaxsourcetype', native_enum=False, length=20), nullable=True),
    sa.Column('source_id', app.utils.types.GUID(), nullable=True),
    sa.Column('created_by', app.utils.types.GUID(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_income_tax_adjustments_company_fy', 'income_tax_adjustments', ['company_id', 'financial_year_id'], unique=False)
    op.create_index(op.f('ix_income_tax_adjustments_company_id'), 'income_tax_adjustments', ['company_id'], unique=False)
    op.create_index(op.f('ix_income_tax_adjustments_financial_year_id'), 'income_tax_adjustments', ['financial_year_id'], unique=False)
    op.create_table('income_tax_advance_tax_payments',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('challan_number', sa.String(length=50), nullable=True),
    sa.Column('created_by', app.utils.types.GUID(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_income_tax_advance_tax_payments_company_fy', 'income_tax_advance_tax_payments', ['company_id', 'financial_year_id'], unique=False)
    op.create_index(op.f('ix_income_tax_advance_tax_payments_company_id'), 'income_tax_advance_tax_payments', ['company_id'], unique=False)
    op.create_index(op.f('ix_income_tax_advance_tax_payments_financial_year_id'), 'income_tax_advance_tax_payments', ['financial_year_id'], unique=False)
    op.create_table('income_tax_capital_gains',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('EQUITY_SHARES', 'MUTUAL_FUND', 'IMMOVABLE_PROPERTY', 'GOLD_JEWELLERY', 'DEBT_INSTRUMENT', 'OTHER', name='capitalassettype', native_enum=False, length=20), nullable=False),
    sa.Column('asset_description', sa.String(length=500), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('purchase_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('improvement_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('sale_consideration', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('transfer_expenses', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('indexed_cost', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('gain_type', sa.Enum('SHORT_TERM', 'LONG_TERM', name='capitalgaintype', native_enum=False), nullable=False),
    sa.Column('gain_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_income_tax_capital_gains_company_fy', 'income_tax_capital_gains', ['company_id', 'financial_year_id'], unique=False)
    op.create_index(op.f('ix_income_tax_capital_gains_company_id'), 'income_tax_capital_gains', ['company_id'], unique=False)
    op.create_index(op.f('ix_income_tax_capital_gains_financial_year_id'), 'income_tax_capital_gains', ['financial_year_id'], unique=False)
    op.create_table('income_tax_credit_entries',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('deductor_name', sa.String(length=255), nullable=False),
    sa.Column('deductor_tan', sa.String(length=10), nullable=True),
    sa.Column('section_code', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('certificate_reference', sa.String(length=100), nullable=True),
    sa.Column('source_type', sa.Enum('SALES_INVOICE', 'PURCHASE_INVOICE', 'PAYMENT', 'RECEIPT', 'JOURNAL_ENTRY', 'LEDGER', 'DOCUMENT', 'TDS_TRANSACTION', 'OTHER', name='incometaxsourcetype', native_enum=False, length=20), nullable=True),
    sa.Column('source_id', app.utils.types.GUID(), nullable=True),
    sa.Column('created_by', app.utils.types.GUID(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_income_tax_credit_entries_company_fy', 'income_tax_credit_entries', ['company_id', 'financial_year_id'], unique=False)
    op.create_index(op.f('ix_income_tax_credit_entries_company_id'), 'income_tax_credit_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_income_tax_credit_entries_financial_year_id'), 'income_tax_credit_entries', ['financial_year_id'], unique=False)
    op.create_table('income_tax_deductions',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('section_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('claimed_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('eligible_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source_type', sa.Enum('SALES_INVOICE', 'PURCHASE_INVOICE', 'PAYMENT', 'RECEIPT', 'JOURNAL_ENTRY', 'LEDGER', 'DOCUMENT', 'TDS_TRANSACTION', 'OTHER', name='incometaxsourcetype', native_enum=False, length=20), nullable=True),
    sa.Column('source_id', app.utils.types.GUID(), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_income_tax_deductions_company_fy', 'income_tax_deductions', ['company_id', 'financial_year_id'], unique=False)
    op.create_index(op.f('ix_income_tax_deductions_company_id'), 'income_tax_deductions', ['company_id'], unique=False)
    op.create_index(op.f('ix_income_tax_deductions_financial_year_id'), 'income_tax_deductions', ['financial_year_id'], unique=False)
    op.create_table('income_tax_exempt_incomes',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('section_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_income_tax_exempt_incomes_company_fy', 'income_tax_exempt_incomes', ['company_id', 'financial_year_id'], unique=False)
    op.create_index(op.f('ix_income_tax_exempt_incomes_company_id'), 'income_tax_exempt_incomes', ['company_id'], unique=False)
    op.create_index(op.f('ix_income_tax_exempt_incomes_financial_year_id'), 'income_tax_exempt_incomes', ['financial_year_id'], unique=False)
    op.create_table('income_tax_house_property_incomes',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('property_type', sa.Enum('SELF_OCCUPIED', 'LET_OUT', name='housepropertytype', native_enum=False, length=15), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('gross_rent', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('municipal_tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_annual_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('standard_deduction', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest_on_home_loan', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('income_or_loss', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_income_tax_house_property_incomes_company_fy', 'income_tax_house_property_incomes', ['company_id', 'financial_year_id'], unique=False)
    op.create_index(op.f('ix_income_tax_house_property_incomes_company_id'), 'income_tax_house_property_incomes', ['company_id'], unique=False)
    op.create_index(op.f('ix_income_tax_house_property_incomes_financial_year_id'), 'income_tax_house_property_incomes', ['financial_year_id'], unique=False)
    op.create_table('income_tax_ledger_classifications',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('ledger_id', app.utils.types.GUID(), nullable=False),
    sa.Column('classification', sa.Enum('ALLOWABLE', 'PARTIALLY_ALLOWABLE', 'DISALLOWABLE', 'REVIEW_REQUIRED', 'NOT_CLASSIFIED', name='ledgertaxclassification', native_enum=False, length=20), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_tax_ledger_classifications_company_id'), 'income_tax_ledger_classifications', ['company_id'], unique=False)
    op.create_index(op.f('ix_income_tax_ledger_classifications_ledger_id'), 'income_tax_ledger_classifications', ['ledger_id'], unique=False)
    op.create_index('ix_income_tax_ledger_classifications_unique', 'income_tax_ledger_classifications', ['company_id', 'ledger_id'], unique=True)
    op.create_table('income_tax_losses',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('origin_financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('loss_type', sa.Enum('BUSINESS', 'CAPITAL_SHORT_TERM', 'CAPITAL_LONG_TERM', 'HOUSE_PROPERTY', 'OTHER', name='taxlosstype', native_enum=False, length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('setoff_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('carried_forward_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('expiry_financial_year_id', app.utils.types.GUID(), nullable=True),
    sa.Column('created_by', app.utils.types.GUID(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['expiry_financial_year_id'], ['financial_years.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['origin_financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_income_tax_losses_company_fy', 'income_tax_losses', ['company_id', 'origin_financial_year_id'], unique=False)
    op.create_index(op.f('ix_income_tax_losses_company_id'), 'income_tax_losses', ['company_id'], unique=False)
    op.create_index(op.f('ix_income_tax_losses_origin_financial_year_id'), 'income_tax_losses', ['origin_financial_year_id'], unique=False)
    op.create_table('income_tax_other_incomes',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('income_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tds', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source_type', sa.Enum('SALES_INVOICE', 'PURCHASE_INVOICE', 'PAYMENT', 'RECEIPT', 'JOURNAL_ENTRY', 'LEDGER', 'DOCUMENT', 'TDS_TRANSACTION', 'OTHER', name='incometaxsourcetype', native_enum=False, length=20), nullable=True),
    sa.Column('source_id', app.utils.types.GUID(), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_income_tax_other_incomes_company_fy', 'income_tax_other_incomes', ['company_id', 'financial_year_id'], unique=False)
    op.create_index(op.f('ix_income_tax_other_incomes_company_id'), 'income_tax_other_incomes', ['company_id'], unique=False)
    op.create_index(op.f('ix_income_tax_other_incomes_financial_year_id'), 'income_tax_other_incomes', ['financial_year_id'], unique=False)
    op.create_table('income_tax_salary_incomes',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('employer_name', sa.String(length=255), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('allowances', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('perquisites', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('profit_in_lieu', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('standard_deduction', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('professional_tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tds', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_income_tax_salary_incomes_company_fy', 'income_tax_salary_incomes', ['company_id', 'financial_year_id'], unique=False)
    op.create_index(op.f('ix_income_tax_salary_incomes_company_id'), 'income_tax_salary_incomes', ['company_id'], unique=False)
    op.create_index(op.f('ix_income_tax_salary_incomes_financial_year_id'), 'income_tax_salary_incomes', ['financial_year_id'], unique=False)
    op.create_table('income_tax_self_assessment_tax_payments',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('challan_number', sa.String(length=50), nullable=True),
    sa.Column('created_by', app.utils.types.GUID(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_income_tax_self_assessment_tax_payments_company_fy', 'income_tax_self_assessment_tax_payments', ['company_id', 'financial_year_id'], unique=False)
    op.create_index(op.f('ix_income_tax_self_assessment_tax_payments_company_id'), 'income_tax_self_assessment_tax_payments', ['company_id'], unique=False)
    op.create_index(op.f('ix_income_tax_self_assessment_tax_payments_financial_year_id'), 'income_tax_self_assessment_tax_payments', ['financial_year_id'], unique=False)
    op.create_table('tax_computations',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('assessment_year', sa.String(length=10), nullable=False),
    sa.Column('tax_regime', sa.Enum('OLD_REGIME', 'NEW_REGIME', name='taxregime', native_enum=False, length=15), nullable=False),
    sa.Column('rule_set_id', app.utils.types.GUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CALCULATED', 'REVIEW_REQUIRED', 'READY_FOR_REVIEW', 'APPROVED', 'LOCKED', 'CANCELLED', name='taxcomputationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('salary_income', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('house_property_income', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('business_income', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('capital_gains_income', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('other_income', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_total_income', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxable_income', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_before_rebate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('rebate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax_after_rebate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('surcharge', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cess', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gross_tax_liability', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tds_credit_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('advance_tax_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('self_assessment_tax_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_payable_or_refund', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', app.utils.types.GUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', app.utils.types.GUID(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['income_tax_rule_sets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tax_computations_company_fy', 'tax_computations', ['company_id', 'financial_year_id'], unique=False)
    op.create_index(op.f('ix_tax_computations_company_id'), 'tax_computations', ['company_id'], unique=False)
    op.create_index(op.f('ix_tax_computations_financial_year_id'), 'tax_computations', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_tax_computations_status'), 'tax_computations', ['status'], unique=False)
    op.create_table('itr_preparations',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('tax_computation_id', app.utils.types.GUID(), nullable=False),
    sa.Column('itr_form_type', sa.Enum('ITR_1', 'ITR_2', 'ITR_3', 'ITR_5', 'ITR_6', 'ITR_7', 'NOT_DETERMINED', name='itrformtype', native_enum=False, length=20), nullable=False),
    sa.Column('assessment_year', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'VALIDATION_REQUIRED', 'READY_FOR_REVIEW', 'APPROVED', 'LOCKED', name='itrpreparationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('prepared_by', app.utils.types.GUID(), nullable=False),
    sa.Column('reviewed_by', app.utils.types.GUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prepared_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tax_computation_id'], ['tax_computations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itr_preparations_company_id'), 'itr_preparations', ['company_id'], unique=False)
    op.create_index('ix_itr_preparations_computation', 'itr_preparations', ['tax_computation_id'], unique=True)
    op.create_index(op.f('ix_itr_preparations_status'), 'itr_preparations', ['status'], unique=False)
    op.create_index(op.f('ix_itr_preparations_tax_computation_id'), 'itr_preparations', ['tax_computation_id'], unique=False)
    op.create_table('tax_computation_snapshots',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('tax_computation_id', app.utils.types.GUID(), nullable=False),
    sa.Column('rule_set_id', app.utils.types.GUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_by', app.utils.types.GUID(), nullable=True),
    sa.Column('summary_data', sa.JSON(), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['income_tax_rule_sets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tax_computation_id'], ['tax_computations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_computation_snapshots_company_id'), 'tax_computation_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_tax_computation_snapshots_tax_computation_id'), 'tax_computation_snapshots', ['tax_computation_id'], unique=False)
    op.create_index('ix_tax_computation_snapshots_unique_version', 'tax_computation_snapshots', ['tax_computation_id', 'version'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tax_computation_snapshots_unique_version', table_name='tax_computation_snapshots')
    op.drop_index(op.f('ix_tax_computation_snapshots_tax_computation_id'), table_name='tax_computation_snapshots')
    op.drop_index(op.f('ix_tax_computation_snapshots_company_id'), table_name='tax_computation_snapshots')
    op.drop_table('tax_computation_snapshots')
    op.drop_index(op.f('ix_itr_preparations_tax_computation_id'), table_name='itr_preparations')
    op.drop_index(op.f('ix_itr_preparations_status'), table_name='itr_preparations')
    op.drop_index('ix_itr_preparations_computation', table_name='itr_preparations')
    op.drop_index(op.f('ix_itr_preparations_company_id'), table_name='itr_preparations')
    op.drop_table('itr_preparations')
    op.drop_index(op.f('ix_tax_computations_status'), table_name='tax_computations')
    op.drop_index(op.f('ix_tax_computations_financial_year_id'), table_name='tax_computations')
    op.drop_index(op.f('ix_tax_computations_company_id'), table_name='tax_computations')
    op.drop_index('ix_tax_computations_company_fy', table_name='tax_computations')
    op.drop_table('tax_computations')
    op.drop_index(op.f('ix_income_tax_self_assessment_tax_payments_financial_year_id'), table_name='income_tax_self_assessment_tax_payments')
    op.drop_index(op.f('ix_income_tax_self_assessment_tax_payments_company_id'), table_name='income_tax_self_assessment_tax_payments')
    op.drop_index('ix_income_tax_self_assessment_tax_payments_company_fy', table_name='income_tax_self_assessment_tax_payments')
    op.drop_table('income_tax_self_assessment_tax_payments')
    op.drop_index(op.f('ix_income_tax_salary_incomes_financial_year_id'), table_name='income_tax_salary_incomes')
    op.drop_index(op.f('ix_income_tax_salary_incomes_company_id'), table_name='income_tax_salary_incomes')
    op.drop_index('ix_income_tax_salary_incomes_company_fy', table_name='income_tax_salary_incomes')
    op.drop_table('income_tax_salary_incomes')
    op.drop_index(op.f('ix_income_tax_other_incomes_financial_year_id'), table_name='income_tax_other_incomes')
    op.drop_index(op.f('ix_income_tax_other_incomes_company_id'), table_name='income_tax_other_incomes')
    op.drop_index('ix_income_tax_other_incomes_company_fy', table_name='income_tax_other_incomes')
    op.drop_table('income_tax_other_incomes')
    op.drop_index(op.f('ix_income_tax_losses_origin_financial_year_id'), table_name='income_tax_losses')
    op.drop_index(op.f('ix_income_tax_losses_company_id'), table_name='income_tax_losses')
    op.drop_index('ix_income_tax_losses_company_fy', table_name='income_tax_losses')
    op.drop_table('income_tax_losses')
    op.drop_index('ix_income_tax_ledger_classifications_unique', table_name='income_tax_ledger_classifications')
    op.drop_index(op.f('ix_income_tax_ledger_classifications_ledger_id'), table_name='income_tax_ledger_classifications')
    op.drop_index(op.f('ix_income_tax_ledger_classifications_company_id'), table_name='income_tax_ledger_classifications')
    op.drop_table('income_tax_ledger_classifications')
    op.drop_index(op.f('ix_income_tax_house_property_incomes_financial_year_id'), table_name='income_tax_house_property_incomes')
    op.drop_index(op.f('ix_income_tax_house_property_incomes_company_id'), table_name='income_tax_house_property_incomes')
    op.drop_index('ix_income_tax_house_property_incomes_company_fy', table_name='income_tax_house_property_incomes')
    op.drop_table('income_tax_house_property_incomes')
    op.drop_index(op.f('ix_income_tax_exempt_incomes_financial_year_id'), table_name='income_tax_exempt_incomes')
    op.drop_index(op.f('ix_income_tax_exempt_incomes_company_id'), table_name='income_tax_exempt_incomes')
    op.drop_index('ix_income_tax_exempt_incomes_company_fy', table_name='income_tax_exempt_incomes')
    op.drop_table('income_tax_exempt_incomes')
    op.drop_index(op.f('ix_income_tax_deductions_financial_year_id'), table_name='income_tax_deductions')
    op.drop_index(op.f('ix_income_tax_deductions_company_id'), table_name='income_tax_deductions')
    op.drop_index('ix_income_tax_deductions_company_fy', table_name='income_tax_deductions')
    op.drop_table('income_tax_deductions')
    op.drop_index(op.f('ix_income_tax_credit_entries_financial_year_id'), table_name='income_tax_credit_entries')
    op.drop_index(op.f('ix_income_tax_credit_entries_company_id'), table_name='income_tax_credit_entries')
    op.drop_index('ix_income_tax_credit_entries_company_fy', table_name='income_tax_credit_entries')
    op.drop_table('income_tax_credit_entries')
    op.drop_index(op.f('ix_income_tax_capital_gains_financial_year_id'), table_name='income_tax_capital_gains')
    op.drop_index(op.f('ix_income_tax_capital_gains_company_id'), table_name='income_tax_capital_gains')
    op.drop_index('ix_income_tax_capital_gains_company_fy', table_name='income_tax_capital_gains')
    op.drop_table('income_tax_capital_gains')
    op.drop_index(op.f('ix_income_tax_advance_tax_payments_financial_year_id'), table_name='income_tax_advance_tax_payments')
    op.drop_index(op.f('ix_income_tax_advance_tax_payments_company_id'), table_name='income_tax_advance_tax_payments')
    op.drop_index('ix_income_tax_advance_tax_payments_company_fy', table_name='income_tax_advance_tax_payments')
    op.drop_table('income_tax_advance_tax_payments')
    op.drop_index(op.f('ix_income_tax_adjustments_financial_year_id'), table_name='income_tax_adjustments')
    op.drop_index(op.f('ix_income_tax_adjustments_company_id'), table_name='income_tax_adjustments')
    op.drop_index('ix_income_tax_adjustments_company_fy', table_name='income_tax_adjustments')
    op.drop_table('income_tax_adjustments')
    op.drop_index(op.f('ix_income_tax_surcharge_rules_rule_set_id'), table_name='income_tax_surcharge_rules')
    op.drop_index('ix_income_tax_surcharge_rules_rule_set', table_name='income_tax_surcharge_rules')
    op.drop_table('income_tax_surcharge_rules')
    op.drop_index(op.f('ix_income_tax_slabs_rule_set_id'), table_name='income_tax_slabs')
    op.drop_index('ix_income_tax_slabs_rule_set', table_name='income_tax_slabs')
    op.drop_table('income_tax_slabs')
    op.drop_index(op.f('ix_income_tax_rebate_rules_rule_set_id'), table_name='income_tax_rebate_rules')
    op.drop_index('ix_income_tax_rebate_rules_rule_set', table_name='income_tax_rebate_rules')
    op.drop_table('income_tax_rebate_rules')
    op.drop_index('ix_income_tax_profiles_company_unique', table_name='income_tax_profiles')
    op.drop_index(op.f('ix_income_tax_profiles_company_id'), table_name='income_tax_profiles')
    op.drop_table('income_tax_profiles')
    op.drop_index('ix_income_tax_deduction_rules_unique', table_name='income_tax_deduction_rules')
    op.drop_index(op.f('ix_income_tax_deduction_rules_rule_set_id'), table_name='income_tax_deduction_rules')
    op.drop_table('income_tax_deduction_rules')
    op.drop_index('ix_income_tax_rule_sets_unique_version', table_name='income_tax_rule_sets')
    op.drop_index(op.f('ix_income_tax_rule_sets_taxpayer_type'), table_name='income_tax_rule_sets')
    op.drop_index(op.f('ix_income_tax_rule_sets_tax_regime'), table_name='income_tax_rule_sets')
    op.drop_index(op.f('ix_income_tax_rule_sets_assessment_year'), table_name='income_tax_rule_sets')
    op.drop_table('income_tax_rule_sets')
    # ### end Alembic commands ###
