"""add_tds_transactions

Revision ID: f9f81c3b679b
Revises: 6b98c35e3d5c
Create Date: 2026-09-18 10:00:57.643842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.utils.types


# revision identifiers, used by Alembic.
revision: str = 'f9f81c3b679b'
down_revision: Union[str, None] = '6b98c35e3d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tds_transactions',
    sa.Column('company_id', app.utils.types.GUID(), nullable=False),
    sa.Column('financial_year_id', app.utils.types.GUID(), nullable=False),
    sa.Column('deductee_id', app.utils.types.GUID(), nullable=False),
    sa.Column('tds_section_id', app.utils.types.GUID(), nullable=False),
    sa.Column('tds_rule_id', app.utils.types.GUID(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('source_id', app.utils.types.GUID(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'CSV', 'EXCEL', 'TALLY', name='datasource', native_enum=False, length=10), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('deduction_date', sa.Date(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tds_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tds_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('pan_status', sa.Enum('AVAILABLE', 'NOT_AVAILABLE', 'INVALID', 'PENDING_REVIEW', name='panstatus', native_enum=False, length=15), nullable=False),
    sa.Column('applicability_status', sa.Enum('APPLICABLE', 'NOT_APPLICABLE', 'REVIEW_REQUIRED', 'MISSING_DATA', name='tdsapplicabilitystatus', native_enum=False, length=20), nullable=True),
    sa.Column('applicability_reason', sa.String(length=500), nullable=True),
    sa.Column('system_calculated_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.String(length=500), nullable=True),
    sa.Column('overridden_by', app.utils.types.GUID(), nullable=True),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'CALCULATED', 'DEDUCTED', 'PAID', 'CANCELLED', 'REVIEW_REQUIRED', name='tdstransactionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', app.utils.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deductee_id'], ['deductees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['overridden_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tds_rule_id'], ['tds_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tds_section_id'], ['tds_sections.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tds_transactions_company_date', 'tds_transactions', ['company_id', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_tds_transactions_company_id'), 'tds_transactions', ['company_id'], unique=False)
    op.create_index('ix_tds_transactions_company_status', 'tds_transactions', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_tds_transactions_deductee_id'), 'tds_transactions', ['deductee_id'], unique=False)
    op.create_index(op.f('ix_tds_transactions_deduction_date'), 'tds_transactions', ['deduction_date'], unique=False)
    op.create_index(op.f('ix_tds_transactions_financial_year_id'), 'tds_transactions', ['financial_year_id'], unique=False)
    op.create_index(op.f('ix_tds_transactions_status'), 'tds_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_tds_transactions_tds_section_id'), 'tds_transactions', ['tds_section_id'], unique=False)
    op.create_index(op.f('ix_tds_transactions_transaction_date'), 'tds_transactions', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tds_transactions_transaction_date'), table_name='tds_transactions')
    op.drop_index(op.f('ix_tds_transactions_tds_section_id'), table_name='tds_transactions')
    op.drop_index(op.f('ix_tds_transactions_status'), table_name='tds_transactions')
    op.drop_index(op.f('ix_tds_transactions_financial_year_id'), table_name='tds_transactions')
    op.drop_index(op.f('ix_tds_transactions_deduction_date'), table_name='tds_transactions')
    op.drop_index(op.f('ix_tds_transactions_deductee_id'), table_name='tds_transactions')
    op.drop_index('ix_tds_transactions_company_status', table_name='tds_transactions')
    op.drop_index(op.f('ix_tds_transactions_company_id'), table_name='tds_transactions')
    op.drop_index('ix_tds_transactions_company_date', table_name='tds_transactions')
    op.drop_table('tds_transactions')
    # ### end Alembic commands ###
